import "server-only";

export const REAL_MENSWEAR_MATERIAL_TERMS = [
  "100% linen",
  "100% linen shirting",
  "170s shirting",
  "1772 Flannel",
  "21 Micron Wool",
  "3/300s yarn count",
  "6-ply",
  "all-wool suiting",
  "Australian wool",
  "Baby Alpaca",
  "bamboo-linen blend",
  "batiste",
  "Beausoleil",
  "bouclé fabric",
  "bouclé yarn",
  "Brera Sportcoat wool-silk",
  "brushed cotton",
  "camel",
  "Carnival mohair-wool",
  "cashmere",
  "Cashmere 4.0",
  "cashmere cloth",
  "Cashmere Fleece",
  "Cashmerello",
  "Chinese silk",
  "Classic Flannel",
  "coating cloth",
  "colored nepps",
  "combed long-staple cotton",
  "corduroy",
  "corduroy cotton",
  "cotton",
  "cotton gabardine",
  "cotton poplin",
  "cotton tricotine",
  "cotton-linen",
  "cotton-linen shirting",
  "cotton-silk shirting",
  "covert",
  "covert cloth",
  "délavé linen",
  "Double",
  "easy-care finish",
  "Egyptian Giza 45 cotton",
  "Egyptian Giza 87 cotton",
  "Escorial wool",
  "European flax linen",
  "extra-fine worsted wool",
  "extra-long-staple cotton",
  "felted fabric",
  "flannel cloth",
  "flannel shirting",
  "flat cotton",
  "Fox Air",
  "Fox City",
  "Fox Jacketing",
  "Fox Khaki",
  "Fox Linen",
  "Fox Lining",
  "Fox Tweed",
  "Functional Fabrics",
  "Golden Fox",
  "GREENHILLS Super 180s",
  "greige raw fabric",
  "heavy Oxford",
  "heavy twill",
  "herringbone semi-plain",
  "herringbone shirting",
  "high-end natural fabric",
  "high-end natural fabrics",
  "hopsack",
  "indigo yarn fabric",
  "Irish linen",
  "jacketing cloth",
  "jacketing fabric",
  "jacquard",
  "jacquard fabric",
  "jacquard linen",
  "jacquard shirting",
  "jersey fabric",
  "Kid Cashmere",
  "Kid Wool 12.8",
  "Knit Icons",
  "knit-look fabric",
  "lightweight casual fabric",
  "linen",
  "Linen and the Gang",
  "linen fabric",
  "linen shirting",
  "llama",
  "London Shrunk finish",
  "long-staple cotton",
  "Machine Washable",
  "madras linen",
  "Marcella pique",
  "melange fabric",
  "melange linen",
  "Merino wool suiting",
  "mohair",
  "mohair cloth",
  "moleskin",
  "moleskin cotton",
  "Mongolian cashmere",
  "mouliné yarn",
  "natural recycled fibre fabric",
  "Natural Stretch",
  "natural-dyed fabric",
  "natural-flexibility wool",
  "Ne 100/2",
  "Ne 120/2",
  "Ne 170/2",
  "Ne 240/2",
  "Ne 80/2",
  "New Zealand wool",
  "non-iron finish",
  "non-iron sateen",
  "non-iron twill",
  "Oasi Cashmere",
  "Oasi Lino",
  "organic cotton",
  "organzine yarn",
  "overchecked linen",
  "overcoating",
  "Oxford",
  "Oxford shirting",
  "Panama design",
  "Panama weave",
  "Perennial",
  "piece-dyed seersucker",
  "pinpoint shirting",
  "polo Oxford",
  "poplin",
  "poplin shirting",
  "Precious Fabrics",
  "printed fabric",
  "printed shirting",
  "pure silk",
  "pure wool cloth",
  "regenerative cotton",
  "Revenge Super 150s",
  "Royal Oxford",
  "Royal Plume fancy suiting",
  "Royal Twill",
  "Rustic Tropical",
  "Sartoria Ceremony",
  "Sartoria Contemporary",
  "Sartoria Timeless",
  "Sartoria White & Colors",
  "sateen shirting",
  "Saxon Merino Wool",
  "Saxony",
  "Sea Island cotton",
  "seersucker effect",
  "silk",
  "silk cloth",
  "silk fabric",
  "single-ply cotton yarn",
  "Skyfall 14.5 micron",
  "Skyfall Velvet",
  "Solaro Made in Italy",
  "Somerset Jacketing",
  "South African mohair",
  "Soyella",
  "Sports Jacketing",
  "spray-dyed fabric",
  "Spring 4-ply",
  "spun silk",
  "stretch fabric",
  "stretch shirting",
  "striped linen",
  "suiting cloth",
  "suiting fabric",
  "summer tailoring cloth",
  "Super 130s wool",
  "Super 140s wool",
  "Super 210s wool",
  "Super 230s wool",
  "Superbio",
  "superfine wool",
  "Superior",
  "Supima cotton",
  "Supraluxe",
  "Swing Natural B Stretch",
  "The Mohair Affair",
  "travel suiting",
  "Traveller shirting",
  "tropical",
  "Tropical Worsted",
  "tweed",
  "twill",
  "twill shirting",
  "Twill Soprano",
  "two-ply cotton yarn",
  "undyed fabric",
  "velvet",
  "velvet cotton",
  "Vicuña",
  "vicuña",
  "viscose-acetate lining",
  "voile",
  "Voyage",
  "water-and-stain-repellent wool",
  "wool",
  "Wool & Mohair",
  "wool-cashmere-mohair blend",
  "wool-cotton blend",
  "woollen",
  "woollen flannel",
  "worsted",
  "Worsted Classics",
  "Worsted Flannel",
  "worsted flannel",
  "Yangir",
  "yarn-dyed linen",
  "yarn-dyed seersucker",
  "yarn-dyed shirting",
  "Zephir"
] as const;

export const REAL_MENSWEAR_PATTERN_TERMS = [
  "2 x 1 Oxford weave",
  "2 x 1 twill",
  "2 x 2 basket weave",
  "2 x 2 twill",
  "Barathea",
  "Barley Corn",
  "Barlycorn Herringbone with Windowpane Check",
  "Bedford cord",
  "Bird's eye",
  "birdseye",
  "Bold stripe",
  "Bold Windowpane",
  "boucle",
  "bouclé effect",
  "British checks and plains",
  "Brushed twill",
  "Camouflage",
  "chain stripe",
  "Chalk stripe",
  "check",
  "Check Structured",
  "Chevron weave",
  "Classic checks",
  "Classic stripes",
  "Clip-spot",
  "colored nepp effect",
  "corduroy",
  "Country check",
  "Dobby",
  "Dobby geometric",
  "Earthy plains",
  "End-on-end",
  "false plain",
  "Fancy Check",
  "Fancy Herringbone",
  "Fancy suiting",
  "Flannel checks",
  "gabardine",
  "Glen check",
  "Glen Check with Guarded Check",
  "Glen Check with Windowpane Overcheck",
  "Gunclub Check with Windowpane Check",
  "Heavy waffle weave pique",
  "herringbone",
  "herringbone semi-plain",
  "hopsack",
  "hopsack check",
  "Hopsack cloth",
  "jacquard",
  "Jacquard large repeat",
  "jacquard pattern",
  "jersey",
  "left-hand twill",
  "Leno mesh",
  "Light Panama",
  "madras",
  "marle",
  "melange",
  "Melange checks",
  "Mesh",
  "micro design",
  "micro jacquard effect",
  "micro pattern",
  "Micro Weave",
  "Micro-design",
  "moleskin",
  "mouliné effect",
  "mouline twill",
  "overcheck",
  "Oxford",
  "Panama designs",
  "Pattern stripe dobby",
  "Pencil stripe",
  "Pick and Pick",
  "pick-and-pick",
  "pin head",
  "pin stripe",
  "Pindot",
  "poplin",
  "Poplin stripes",
  "Prince of Wales",
  "Prince of Wales checks",
  "print",
  "printed pattern",
  "raw weave structure",
  "Reverse Twill Dobby",
  "right-hand twill",
  "rope stripe",
  "Royal Oxford checks",
  "Royal Oxford stripes",
  "Seersucker effect",
  "semi plain",
  "shadow stripe",
  "Shepherd Check",
  "Small check",
  "Solid Plain Structured",
  "Spot weave",
  "spray-dyed design",
  "Stitch Stripe",
  "stripe",
  "Tartan check",
  "Traditional tweed",
  "Tropical weave",
  "twill",
  "Twill checks",
  "Two Tone Narrow Herringbone",
  "Two Tone Twill",
  "Two Tone Wide Herringbone",
  "Two Tone Windowpane Herringbone",
  "velvet",
  "velvet surface",
  "Vintage Twist Herringbone",
  "Weather-resistant plain weave",
  "Weft-way stripe",
  "White-on-white",
  "wide pinstripe",
  "Wild Herringbone Dobby",
  "windowpane",
  "Windowpane Herringbone",
  "yarn-dyed",
  "yarn-dyed pattern",
  "yarn-dyed stripe",
  "Zephyr"
] as const;

export const STANDARD_COLOR_REFERENCE_TERMS = [
  "aliceblue",
  "antiquewhite",
  "aqua",
  "aquamarine",
  "azure",
  "beige",
  "bisque",
  "black",
  "blackish blue",
  "blackish green",
  "blackish purple",
  "blackish red",
  "blanchedalmond",
  "blue",
  "blueviolet",
  "bluish black",
  "bluish gray",
  "bluish white",
  "brilliant blue",
  "brilliant bluish green",
  "brilliant green",
  "brilliant greenish blue",
  "brilliant greenish yellow",
  "brilliant orange",
  "brilliant orange yellow",
  "brilliant purple",
  "brilliant purplish blue",
  "brilliant purplish pink",
  "brilliant violet",
  "brilliant yellow",
  "brilliant yellow green",
  "brilliant yellowish green",
  "brown",
  "brownish black",
  "brownish gray",
  "brownish orange",
  "brownish pink",
  "burlywood",
  "cadetblue",
  "chartreuse",
  "chocolate",
  "coral",
  "cornflowerblue",
  "cornsilk",
  "crimson",
  "cyan",
  "dark blue",
  "dark bluish gray",
  "dark bluish green",
  "dark brown",
  "dark gray",
  "dark grayish blue",
  "dark grayish brown",
  "dark grayish green",
  "dark grayish olive",
  "dark grayish olive green",
  "dark grayish purple",
  "dark grayish red",
  "dark grayish reddish brown",
  "dark grayish yellow",
  "dark grayish yellow brown",
  "dark green",
  "dark greenish blue",
  "dark greenish gray",
  "dark greenish yellow",
  "dark olive",
  "dark olive brown",
  "dark olive green",
  "dark orange yellow",
  "dark pink",
  "dark purple",
  "dark purplish blue",
  "dark purplish gray",
  "dark purplish pink",
  "dark purplish red",
  "dark red",
  "dark reddish brown",
  "dark reddish gray",
  "dark reddish orange",
  "dark reddish purple",
  "dark violet",
  "dark yellow",
  "dark yellowish brown",
  "dark yellowish green",
  "dark yellowish pink",
  "darkblue",
  "darkcyan",
  "darkgoldenrod",
  "darkgray",
  "darkgreen",
  "darkgrey",
  "darkkhaki",
  "darkmagenta",
  "darkolivegreen",
  "darkorange",
  "darkorchid",
  "darkred",
  "darksalmon",
  "darkseagreen",
  "darkslateblue",
  "darkslategray",
  "darkslategrey",
  "darkturquoise",
  "darkviolet",
  "deep blue",
  "deep bluish green",
  "deep brown",
  "deep green",
  "deep greenish blue",
  "deep greenish yellow",
  "deep olive green",
  "deep orange",
  "deep orange yellow",
  "deep pink",
  "deep purple",
  "deep purplish blue",
  "deep purplish pink",
  "deep purplish red",
  "deep red",
  "deep reddish brown",
  "deep reddish orange",
  "deep reddish purple",
  "deep violet",
  "deep yellow",
  "deep yellow green",
  "deep yellowish brown",
  "deep yellowish green",
  "deep yellowish pink",
  "deeppink",
  "deepskyblue",
  "dimgray",
  "dimgrey",
  "dodgerblue",
  "firebrick",
  "floralwhite",
  "forestgreen",
  "fuchsia",
  "gainsboro",
  "ghostwhite",
  "gold",
  "goldenrod",
  "gray",
  "grayish blue",
  "grayish brown",
  "grayish green",
  "grayish greenish yellow",
  "grayish olive",
  "grayish olive green",
  "grayish pink",
  "grayish purple",
  "grayish purplish blue",
  "grayish purplish pink",
  "grayish purplish red",
  "grayish red",
  "grayish reddish brown",
  "grayish reddish orange",
  "grayish reddish purple",
  "grayish violet",
  "grayish yellow",
  "grayish yellow green",
  "grayish yellowish brown",
  "grayish yellowish pink",
  "green",
  "greenish black",
  "greenish gray",
  "greenish white",
  "greenyellow",
  "grey",
  "honeydew",
  "hotpink",
  "indianred",
  "indigo",
  "ivory",
  "khaki",
  "lavender",
  "lavenderblush",
  "lawngreen",
  "lemonchiffon",
  "light blue",
  "light bluish gray",
  "light bluish green",
  "light brown",
  "light brownish gray",
  "light gray",
  "light grayish brown",
  "light grayish olive",
  "light grayish purplish red",
  "light grayish red",
  "light grayish reddish brown",
  "light grayish yellowish brown",
  "light green",
  "light greenish blue",
  "light greenish gray",
  "light greenish yellow",
  "light olive",
  "light olive brown",
  "light olive gray",
  "light orange",
  "light orange yellow",
  "light pink",
  "light purple",
  "light purplish blue",
  "light purplish gray",
  "light purplish pink",
  "light reddish brown",
  "light reddish purple",
  "light violet",
  "light yellow",
  "light yellow green",
  "light yellowish brown",
  "light yellowish green",
  "light yellowish pink",
  "lightblue",
  "lightcoral",
  "lightcyan",
  "lightgoldenrodyellow",
  "lightgray",
  "lightgreen",
  "lightgrey",
  "lightpink",
  "lightsalmon",
  "lightseagreen",
  "lightskyblue",
  "lightslategray",
  "lightslategrey",
  "lightsteelblue",
  "lightyellow",
  "lime",
  "limegreen",
  "linen",
  "magenta",
  "maroon",
  "medium gray",
  "mediumaquamarine",
  "mediumblue",
  "mediumorchid",
  "mediumpurple",
  "mediumseagreen",
  "mediumslateblue",
  "mediumspringgreen",
  "mediumturquoise",
  "mediumvioletred",
  "midnightblue",
  "mintcream",
  "mistyrose",
  "moccasin",
  "moderate blue",
  "moderate bluish green",
  "moderate brown",
  "moderate green",
  "moderate greenish blue",
  "moderate greenish yellow",
  "moderate olive",
  "moderate olive brown",
  "moderate olive green",
  "moderate orange",
  "moderate orange yellow",
  "moderate pink",
  "moderate purple",
  "moderate purplish blue",
  "moderate purplish pink",
  "moderate purplish red",
  "moderate red",
  "moderate reddish brown",
  "moderate reddish orange",
  "moderate reddish purple",
  "moderate violet",
  "moderate yellow",
  "moderate yellow green",
  "moderate yellowish brown",
  "moderate yellowish green",
  "moderate yellowish pink",
  "navajowhite",
  "navy",
  "oldlace",
  "olive",
  "olive black",
  "olive gray",
  "olivedrab",
  "orange",
  "orangered",
  "orchid",
  "pale blue",
  "pale green",
  "pale greenish yellow",
  "pale orange yellow",
  "pale pink",
  "pale purple",
  "pale purplish blue",
  "pale purplish pink",
  "pale reddish purple",
  "pale violet",
  "pale yellow",
  "pale yellow green",
  "pale yellowish pink",
  "palegoldenrod",
  "palegreen",
  "paleturquoise",
  "palevioletred",
  "papayawhip",
  "peachpuff",
  "peru",
  "pink",
  "pinkish gray",
  "pinkish white",
  "plum",
  "powderblue",
  "purple",
  "purplish black",
  "purplish gray",
  "purplish white",
  "rebeccapurple",
  "red",
  "reddish black",
  "reddish gray",
  "rosybrown",
  "royalblue",
  "saddlebrown",
  "salmon",
  "sandybrown",
  "seagreen",
  "seashell",
  "sienna",
  "silver",
  "skyblue",
  "slateblue",
  "slategray",
  "slategrey",
  "snow",
  "springgreen",
  "steelblue",
  "strong blue",
  "strong bluish green",
  "strong brown",
  "strong green",
  "strong greenish blue",
  "strong greenish yellow",
  "strong olive green",
  "strong orange",
  "strong orange yellow",
  "strong pink",
  "strong purple",
  "strong purplish blue",
  "strong purplish pink",
  "strong purplish red",
  "strong red",
  "strong reddish brown",
  "strong reddish orange",
  "strong reddish purple",
  "strong violet",
  "strong yellow",
  "strong yellow green",
  "strong yellowish brown",
  "strong yellowish green",
  "strong yellowish pink",
  "tan",
  "teal",
  "thistle",
  "tomato",
  "turquoise",
  "very dark bluish green",
  "very dark green",
  "very dark greenish blue",
  "very dark purple",
  "very dark purplish red",
  "very dark red",
  "very dark reddish purple",
  "very dark yellowish green",
  "very deep purple",
  "very deep purplish red",
  "very deep red",
  "very deep reddish purple",
  "very deep yellowish green",
  "very light blue",
  "very light bluish green",
  "very light green",
  "very light greenish blue",
  "very light purple",
  "very light purplish blue",
  "very light violet",
  "very light yellowish green",
  "very pale blue",
  "very pale green",
  "very pale purple",
  "very pale purplish blue",
  "very pale violet",
  "violet",
  "vivid blue",
  "vivid bluish green",
  "vivid green",
  "vivid greenish blue",
  "vivid greenish yellow",
  "vivid orange",
  "vivid orange yellow",
  "vivid pink",
  "vivid purple",
  "vivid purplish blue",
  "vivid purplish red",
  "vivid red",
  "vivid reddish orange",
  "vivid reddish purple",
  "vivid violet",
  "vivid yellow",
  "vivid yellow green",
  "vivid yellowish green",
  "vivid yellowish pink",
  "wheat",
  "white",
  "whitesmoke",
  "yellow",
  "yellowgreen",
  "yellowish gray",
  "yellowish white"
] as const;

export const FABRIC_REFERENCE_SOURCES = [
  {
    "id": "acorn",
    "title": "Acorn Shirting Fabrics",
    "publisher": "Acorn Fabrics",
    "url": "https://www.acornfabrics.com/"
  },
  {
    "id": "albiate1830",
    "title": "Albiate 1830",
    "publisher": "Albiate 1830",
    "url": "https://www.albiate1830.com/en/profile/"
  },
  {
    "id": "albini1876",
    "title": "Albini 1876",
    "publisher": "Albini 1876",
    "url": "https://www.albini1876.com/"
  },
  {
    "id": "alumo",
    "title": "ALUMO Shirting Fabrics",
    "publisher": "ALUMO",
    "url": "https://www.alumo.ch/en/textile"
  },
  {
    "id": "ariston",
    "title": "Ariston Fabrics",
    "publisher": "Ariston",
    "url": "https://www.aristonfabrics.com/"
  },
  {
    "id": "bateman-ogden",
    "title": "Bateman & Ogden",
    "publisher": "Bateman & Ogden",
    "url": "https://www.batemanogden.co.uk/"
  },
  {
    "id": "brisbane-moss",
    "title": "Brisbane Moss",
    "publisher": "Brisbane Moss",
    "url": "https://www.brisbanemoss.co.uk/products/"
  },
  {
    "id": "caccioppoli",
    "title": "Caccioppoli Napoli",
    "publisher": "Caccioppoli Napoli",
    "url": "https://www.caccioppolinapoli.it/en/company/"
  },
  {
    "id": "canepa",
    "title": "Canepa Fabric Division",
    "publisher": "Canepa",
    "url": "https://www.canepa.it/en/products/fabric"
  },
  {
    "id": "lenzing",
    "title": "Cellulosic fiber knowledge",
    "publisher": "Lenzing",
    "url": "https://www.lenzing.com/products"
  },
  {
    "id": "cottonworks",
    "title": "Cotton textile education",
    "publisher": "CottonWorks",
    "url": "https://cottonworks.com/"
  },
  {
    "id": "w3c-css-color",
    "title": "CSS Color Module",
    "publisher": "W3C",
    "url": "https://www.w3.org/TR/css-color/"
  },
  {
    "id": "dormeuil",
    "title": "Dormeuil Fabrics",
    "publisher": "Dormeuil",
    "url": "https://dormeuil.com/collections/fabric-fabric"
  },
  {
    "id": "drago",
    "title": "Drago Lanificio in Biella",
    "publisher": "Drago",
    "url": "https://www.dragobiella.it/en/collection/"
  },
  {
    "id": "dugdale",
    "title": "Dugdale Bros & Co",
    "publisher": "Dugdale Bros & Co",
    "url": "https://www.dugdalebros.com/collections/"
  },
  {
    "id": "flaxlinenhemp",
    "title": "European flax and linen knowledge",
    "publisher": "Alliance for European Flax-Linen & Hemp",
    "url": "https://allianceflaxlinenhemp.eu/"
  },
  {
    "id": "ferla",
    "title": "Ferla",
    "publisher": "Lanificio Egidio Ferla",
    "url": "https://www.ferla.it/eng/index.php"
  },
  {
    "id": "alliance-flax",
    "title": "Flax Performance and Properties",
    "publisher": "Alliance for European Flax-Linen & Hemp",
    "url": "https://allianceflaxlinenhemp.eu/en/flax-performance-and-properties"
  },
  {
    "id": "fox-brothers",
    "title": "Fox Brothers Cloth",
    "publisher": "Fox Brothers & Co",
    "url": "https://foxflannel.com/collections/cloth-shop"
  },
  {
    "id": "tallia-delfino",
    "title": "Fratelli Tallia di Delfino",
    "publisher": "Fratelli Tallia di Delfino",
    "url": "https://www.tallia-delfino.com/"
  },
  {
    "id": "getzner",
    "title": "Getzner Textil Shirting",
    "publisher": "Getzner Textil",
    "url": "https://getznerholding.at/en/getzner-textil/"
  },
  {
    "id": "canclini",
    "title": "Grandi & Rubinelli / Canclini",
    "publisher": "Canclini",
    "url": "https://www.canclini.it/en/brands/grandi-rubinelli/collections-gr/"
  },
  {
    "id": "guabello",
    "title": "Guabello",
    "publisher": "Guabello",
    "url": "https://www.guabello.it/en/homepage/"
  },
  {
    "id": "holland-sherry",
    "title": "Holland & Sherry Apparel",
    "publisher": "Holland & Sherry",
    "url": "https://apparel.hollandandsherry.com/"
  },
  {
    "id": "huddersfield",
    "title": "Huddersfield Fine Worsteds",
    "publisher": "Huddersfield Fine Worsteds",
    "url": "https://www.hfwltd.com/"
  },
  {
    "id": "nist-iscc-nbs",
    "title": "ISCC-NBS Color: Universal Language and Dictionary of Names",
    "publisher": "National Institute of Standards and Technology",
    "url": "https://www.nist.gov/publications/color-universal-language-and-dictionary-names"
  },
  {
    "id": "carlo-barbera",
    "title": "Lanificio Carlo Barbera",
    "publisher": "Carlo Barbera",
    "url": "https://www.carlobarbera.it/en/"
  },
  {
    "id": "lanificio-colombo",
    "title": "Lanificio Colombo",
    "publisher": "Lanificio Colombo",
    "url": "https://www.lanificiocolombo.com/"
  },
  {
    "id": "cerruti",
    "title": "Lanificio F.lli Cerruti",
    "publisher": "Lanificio F.lli Cerruti",
    "url": "https://www.lanificiocerruti.com/luxury-man-collection/"
  },
  {
    "id": "subalpino",
    "title": "Lanificio Subalpino",
    "publisher": "Lanificio Subalpino",
    "url": "https://www.lanificiosubalpino.com/en/"
  },
  {
    "id": "loro-piana-textile",
    "title": "Loro Piana Textile",
    "publisher": "Loro Piana",
    "url": "https://www.loropiana.com/textile/"
  },
  {
    "id": "marlane",
    "title": "Marlane",
    "publisher": "Marlane",
    "url": "https://marlane.it/en/"
  },
  {
    "id": "marzotto",
    "title": "Marzotto Tessuti",
    "publisher": "Marzotto Wool Manufacturing",
    "url": "https://www.marzottotessuti.it/en/"
  },
  {
    "id": "hollandsherry",
    "title": "Menswear cloth reference",
    "publisher": "Holland & Sherry",
    "url": "https://www.hollandandsherry.com/"
  },
  {
    "id": "mileta",
    "title": "MILETA Shirting Fabrics",
    "publisher": "MILETA",
    "url": "https://www.mileta.cz/index_en.php?page=our-products"
  },
  {
    "id": "piacenza1733",
    "title": "Piacenza 1733 Fabrics",
    "publisher": "Piacenza 1733",
    "url": "https://fabrics.piacenza1733.com/"
  },
  {
    "id": "reda1865",
    "title": "Reda 1865",
    "publisher": "Reda",
    "url": "https://www.reda1865.com/row/"
  },
  {
    "id": "scabal",
    "title": "Scabal Fabrics",
    "publisher": "Scabal",
    "url": "https://scabal.com/pages/fabrics-collection-ss26"
  },
  {
    "id": "soktas",
    "title": "SÖKTAŞ Shirting Fabrics",
    "publisher": "SÖKTAŞ",
    "url": "https://shop.soktas.com/product-category/all-fabrics/"
  },
  {
    "id": "solbiati",
    "title": "Solbiati",
    "publisher": "Solbiati",
    "url": "https://www.solbiati.it/en/home.html"
  },
  {
    "id": "standeven",
    "title": "Standeven Fabrics",
    "publisher": "Standeven Fabrics",
    "url": "https://www.standevenfabrics.co.uk/pages/cloth"
  },
  {
    "id": "lenzing-lyocell",
    "title": "TENCEL Lyocell",
    "publisher": "Lenzing",
    "url": "https://www.lenzing.com/products/textile-fibers/tenceltm-lyocell/"
  },
  {
    "id": "lenzing-modal",
    "title": "TENCEL Modal",
    "publisher": "Lenzing",
    "url": "https://www.lenzing.com/products/textile-fibers/tenceltm-modal/"
  },
  {
    "id": "monti",
    "title": "Tessitura Monti Shirting",
    "publisher": "Tessitura Monti India",
    "url": "https://www.monti.co.in/"
  },
  {
    "id": "thomas-mason",
    "title": "Thomas Mason Shirting",
    "publisher": "Thomas Mason",
    "url": "https://www.thomasmason.co.uk/"
  },
  {
    "id": "vbc",
    "title": "Vitale Barberis Canonico Fabrics",
    "publisher": "Vitale Barberis Canonico",
    "url": "https://vitalebarberiscanonico.com/collection/fabrics/"
  },
  {
    "id": "woolmark-suiting",
    "title": "Wool Suiting",
    "publisher": "The Woolmark Company",
    "url": "https://www.woolmark.com/z.archive/archive-industry/suiting/"
  },
  {
    "id": "woolmark",
    "title": "Wool textile and apparel knowledge",
    "publisher": "The Woolmark Company",
    "url": "https://www.woolmark.com/industry/"
  },
  {
    "id": "zegna-filiera",
    "title": "Zegna Luxury Textile Laboratory",
    "publisher": "Ermenegildo Zegna Group",
    "url": "https://www.zegnagroup.com/en/our-filiera/"
  }
] as const;

export const REAL_FABRIC_REFERENCE_EXAMPLES = [
  {
    "id": "acorn-windermere-120",
    "sourceId": "acorn",
    "manufacturer": "Acorn Fabrics",
    "productName": "Windermere 2/120s white solid fabric",
    "composition": "",
    "colorName": "White",
    "patternName": "Solid",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": [
      "shirt"
    ]
  },
  {
    "id": "acorn-windsor-140",
    "sourceId": "acorn",
    "manufacturer": "Acorn Fabrics",
    "productName": "Windsor 2/140s white solid fabric",
    "composition": "",
    "colorName": "White",
    "patternName": "Solid",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": [
      "shirt"
    ]
  },
  {
    "id": "dormeuil-191004",
    "sourceId": "dormeuil",
    "manufacturer": "Dormeuil",
    "productName": "Ref 191004",
    "composition": "90% Mohair, 10% Wool",
    "colorName": "Navy",
    "patternName": "Plain",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": []
  },
  {
    "id": "dormeuil-197348",
    "sourceId": "dormeuil",
    "manufacturer": "Dormeuil",
    "productName": "Ref 197348",
    "composition": "70% Wool, 30% Mohair",
    "colorName": "Blue",
    "patternName": "Plain",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": []
  },
  {
    "id": "dormeuil-202455",
    "sourceId": "dormeuil",
    "manufacturer": "Dormeuil",
    "productName": "Ref 202455",
    "composition": "100% Wool",
    "colorName": "Navy",
    "patternName": "Check",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": []
  },
  {
    "id": "dormeuil-202457",
    "sourceId": "dormeuil",
    "manufacturer": "Dormeuil",
    "productName": "Ref 202457",
    "composition": "100% Wool",
    "colorName": "Green",
    "patternName": "Birdseye",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": []
  },
  {
    "id": "dormeuil-417124",
    "sourceId": "dormeuil",
    "manufacturer": "Dormeuil",
    "productName": "Ref 417124",
    "composition": "50% Wool, 30% Silk, 20% Linen",
    "colorName": "Brown",
    "patternName": "Plain",
    "constructionName": "",
    "weightGsm": 220,
    "usageTags": [
      "casual elegance"
    ]
  },
  {
    "id": "dormeuil-417491",
    "sourceId": "dormeuil",
    "manufacturer": "Dormeuil",
    "productName": "Ref 417491",
    "composition": "83% Wool, 17% Linen",
    "colorName": "Brown",
    "patternName": "Check",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": []
  },
  {
    "id": "dormeuil-780023",
    "sourceId": "dormeuil",
    "manufacturer": "Dormeuil",
    "productName": "Ref 780023",
    "composition": "60% Wool, 18% Silk, 16% Polyamide, 6% Linen",
    "colorName": "Brown",
    "patternName": "Check",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": []
  },
  {
    "id": "dormeuil-843370",
    "sourceId": "dormeuil",
    "manufacturer": "Dormeuil",
    "productName": "Ref 843370",
    "composition": "100% Wool",
    "colorName": "Blue",
    "patternName": "Micro Design",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": []
  },
  {
    "id": "dormeuil-880122",
    "sourceId": "dormeuil",
    "manufacturer": "Dormeuil",
    "productName": "Ref 880122",
    "composition": "55% Wool, 45% Silk",
    "colorName": "Blue",
    "patternName": "Check",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": []
  },
  {
    "id": "dormeuil-881150",
    "sourceId": "dormeuil",
    "manufacturer": "Dormeuil",
    "productName": "Ref 881150",
    "composition": "35% Wool, 23% Bamboo, 22% Silk, 20% Linen",
    "colorName": "Purple",
    "patternName": "Plain",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": []
  },
  {
    "id": "dormeuil-881323",
    "sourceId": "dormeuil",
    "manufacturer": "Dormeuil",
    "productName": "Ref 881323",
    "composition": "55% Linen, 45% Wool",
    "colorName": "Orange",
    "patternName": "Plain",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": []
  },
  {
    "id": "dormeuil-882207",
    "sourceId": "dormeuil",
    "manufacturer": "Dormeuil",
    "productName": "Ref 882207",
    "composition": "60% Wool, 40% Linen",
    "colorName": "Beige",
    "patternName": "Herringbone",
    "constructionName": "",
    "weightGsm": 245,
    "usageTags": [
      "casual elegance"
    ]
  },
  {
    "id": "dormeuil-897403",
    "sourceId": "dormeuil",
    "manufacturer": "Dormeuil",
    "productName": "Ref 897403",
    "composition": "85% Wool, 13% Mohair, 2% Lycra",
    "colorName": "Blue",
    "patternName": "Plain",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": []
  },
  {
    "id": "dugdale-2800",
    "sourceId": "dugdale",
    "manufacturer": "Dugdale Bros & Co",
    "productName": "Needle Ready 2800",
    "composition": "100% Wool",
    "colorName": "Grey",
    "patternName": "Subdued Windowpane",
    "constructionName": "Suiting",
    "weightGsm": null,
    "usageTags": [
      "suit",
      "formal wear"
    ]
  },
  {
    "id": "dugdale-2801",
    "sourceId": "dugdale",
    "manufacturer": "Dugdale Bros & Co",
    "productName": "Needle Ready 2801",
    "composition": "100% Wool",
    "colorName": "Navy Blue / Grey",
    "patternName": "Subdued Windowpane",
    "constructionName": "Suiting",
    "weightGsm": null,
    "usageTags": [
      "suit",
      "formal wear"
    ]
  },
  {
    "id": "dugdale-2803",
    "sourceId": "dugdale",
    "manufacturer": "Dugdale Bros & Co",
    "productName": "Needle Ready 2803",
    "composition": "100% Wool",
    "colorName": "Blue / Black",
    "patternName": "Glen Check",
    "constructionName": "Suiting",
    "weightGsm": null,
    "usageTags": [
      "suit",
      "formal wear"
    ]
  },
  {
    "id": "dugdale-2808",
    "sourceId": "dugdale",
    "manufacturer": "Dugdale Bros & Co",
    "productName": "Needle Ready 2808",
    "composition": "100% Wool",
    "colorName": "Navy / Blue",
    "patternName": "Prince of Wales with Blue Overcheck",
    "constructionName": "Suiting",
    "weightGsm": null,
    "usageTags": [
      "suit",
      "formal wear"
    ]
  },
  {
    "id": "dugdale-2813",
    "sourceId": "dugdale",
    "manufacturer": "Dugdale Bros & Co",
    "productName": "Needle Ready 2813",
    "composition": "100% Wool",
    "colorName": "Black / Grey",
    "patternName": "Birdseye",
    "constructionName": "Suiting",
    "weightGsm": null,
    "usageTags": [
      "suit",
      "formal wear"
    ]
  },
  {
    "id": "dugdale-2821",
    "sourceId": "dugdale",
    "manufacturer": "Dugdale Bros & Co",
    "productName": "Needle Ready 2821",
    "composition": "100% Wool",
    "colorName": "Grey",
    "patternName": "Marle with White Chain Stripe",
    "constructionName": "Suiting",
    "weightGsm": null,
    "usageTags": [
      "suit",
      "formal wear"
    ]
  },
  {
    "id": "dugdale-nfw002",
    "sourceId": "dugdale",
    "manufacturer": "Dugdale Bros & Co",
    "productName": "New Fine Worsted Classic NFW002",
    "composition": "100% Wool",
    "colorName": "Grey",
    "patternName": "Marle with Subdued Stripe",
    "constructionName": "Open-weave Worsted",
    "weightGsm": 300,
    "usageTags": [
      "suit",
      "travel"
    ]
  },
  {
    "id": "dugdale-nfw007",
    "sourceId": "dugdale",
    "manufacturer": "Dugdale Bros & Co",
    "productName": "New Fine Worsted Classic NFW007",
    "composition": "100% Wool",
    "colorName": "Navy Blue / Red",
    "patternName": "Pin Stripe",
    "constructionName": "Open-weave Worsted",
    "weightGsm": 300,
    "usageTags": [
      "suit",
      "travel"
    ]
  },
  {
    "id": "dugdale-nfw031",
    "sourceId": "dugdale",
    "manufacturer": "Dugdale Bros & Co",
    "productName": "New Fine Worsted Classic NFW031",
    "composition": "100% Wool",
    "colorName": "Navy Blue / Black",
    "patternName": "Pin Head",
    "constructionName": "Open-weave Worsted",
    "weightGsm": 300,
    "usageTags": [
      "suit",
      "travel"
    ]
  },
  {
    "id": "dugdale-1408",
    "sourceId": "dugdale",
    "manufacturer": "Dugdale Bros & Co",
    "productName": "Royal Classic 1408",
    "composition": "100% Wool",
    "colorName": "Black",
    "patternName": "Wide Ropestripe",
    "constructionName": "Formal Suiting",
    "weightGsm": 340,
    "usageTags": [
      "suit",
      "formal wear"
    ]
  },
  {
    "id": "dugdale-1422",
    "sourceId": "dugdale",
    "manufacturer": "Dugdale Bros & Co",
    "productName": "Royal Classic 1422",
    "composition": "100% Wool",
    "colorName": "Airforce",
    "patternName": "Hopsack Check",
    "constructionName": "Formal Suiting",
    "weightGsm": 340,
    "usageTags": [
      "suit",
      "formal wear"
    ]
  },
  {
    "id": "dugdale-1445",
    "sourceId": "dugdale",
    "manufacturer": "Dugdale Bros & Co",
    "productName": "Royal Classic 1445",
    "composition": "100% Wool",
    "colorName": "Airforce Blue",
    "patternName": "Herringbone",
    "constructionName": "Formal Suiting",
    "weightGsm": 340,
    "usageTags": [
      "suit",
      "formal wear"
    ]
  },
  {
    "id": "dugdale-bur058",
    "sourceId": "dugdale",
    "manufacturer": "Dugdale Bros & Co",
    "productName": "Royal Classic BUR058",
    "composition": "100% Wool",
    "colorName": "Dark Navy Blue",
    "patternName": "Twill",
    "constructionName": "Formal Suiting",
    "weightGsm": 340,
    "usageTags": [
      "suit",
      "formal wear"
    ]
  },
  {
    "id": "piacenza-16-58",
    "sourceId": "piacenza1733",
    "manufacturer": "Piacenza 1733",
    "productName": "Noble Flannel 16/58",
    "composition": "90% Virgin Wool, 10% Cashmere",
    "colorName": "",
    "patternName": "",
    "constructionName": "Flannel",
    "weightGsm": 290,
    "usageTags": [
      "jacket"
    ]
  },
  {
    "id": "piacenza-16-84",
    "sourceId": "piacenza1733",
    "manufacturer": "Piacenza 1733",
    "productName": "Noble Flannel 16/84",
    "composition": "90% Virgin Wool RWS, 10% Cashmere",
    "colorName": "",
    "patternName": "",
    "constructionName": "Flannel",
    "weightGsm": 290,
    "usageTags": [
      "jacket"
    ]
  },
  {
    "id": "piacenza-36-05",
    "sourceId": "piacenza1733",
    "manufacturer": "Piacenza 1733",
    "productName": "Pamir 36/05",
    "composition": "40% Virgin Wool RWS, 60% Cashgora",
    "colorName": "",
    "patternName": "",
    "constructionName": "Pamir / Cashgora blend",
    "weightGsm": 290,
    "usageTags": [
      "jacket"
    ]
  },
  {
    "id": "scabal-brown-houndstooth-overcoat",
    "sourceId": "scabal",
    "manufacturer": "Scabal",
    "productName": "Brown Check Wool Tailored Overcoat",
    "composition": "100% Wool",
    "colorName": "Brown",
    "patternName": "4 colour houndstooth check",
    "constructionName": "Overcoating",
    "weightGsm": 480,
    "usageTags": [
      "overcoat",
      "cold weather"
    ]
  },
  {
    "id": "soktas-alex-f46603-02",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Alex F46603/02",
    "composition": "",
    "colorName": "",
    "patternName": "Prince of Wales checks",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": [
      "shirt"
    ]
  },
  {
    "id": "soktas-alta-f46611-01",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Alta F46611/01",
    "composition": "",
    "colorName": "",
    "patternName": "Poplin stripes",
    "constructionName": "Poplin",
    "weightGsm": null,
    "usageTags": [
      "shirt"
    ]
  },
  {
    "id": "soktas-amelia-f69602-03",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Amelia Melange F69602/03",
    "composition": "",
    "colorName": "",
    "patternName": "Flannel checks",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": [
      "shirt",
      "casual shirt"
    ]
  },
  {
    "id": "soktas-bishop-f55247-01",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Bishop F55247/01",
    "composition": "",
    "colorName": "",
    "patternName": "Twill checks",
    "constructionName": "Twill",
    "weightGsm": null,
    "usageTags": [
      "shirt"
    ]
  },
  {
    "id": "soktas-fiji-f46636-04",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Fiji F46636/04",
    "composition": "",
    "colorName": "",
    "patternName": "Checks",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": [
      "shirt"
    ]
  },
  {
    "id": "soktas-graf-f58207-01",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Graf F58207/01",
    "composition": "",
    "colorName": "",
    "patternName": "Twill checks",
    "constructionName": "Twill",
    "weightGsm": null,
    "usageTags": [
      "shirt"
    ]
  },
  {
    "id": "soktas-graf-f62357-03",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Graf F62357/03",
    "composition": "",
    "colorName": "",
    "patternName": "Twill checks",
    "constructionName": "Twill",
    "weightGsm": null,
    "usageTags": [
      "shirt"
    ]
  },
  {
    "id": "soktas-lazarra-f85475-01",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Lazarra Poplin F85475/01",
    "composition": "",
    "colorName": "",
    "patternName": "",
    "constructionName": "Cotton-Linen Melange Poplin",
    "weightGsm": null,
    "usageTags": [
      "shirt"
    ]
  },
  {
    "id": "soktas-leeds-f62391-09",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Leeds F62391/09",
    "composition": "",
    "colorName": "",
    "patternName": "Royal Oxford stripes",
    "constructionName": "Royal Oxford",
    "weightGsm": null,
    "usageTags": [
      "shirt"
    ]
  },
  {
    "id": "soktas-leeds-f62392-01",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Leeds F62392/01",
    "composition": "",
    "colorName": "",
    "patternName": "Royal Oxford checks",
    "constructionName": "Royal Oxford",
    "weightGsm": null,
    "usageTags": [
      "shirt"
    ]
  },
  {
    "id": "soktas-leeds-f62392-02",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Leeds F62392/02",
    "composition": "",
    "colorName": "",
    "patternName": "Royal Oxford checks",
    "constructionName": "Royal Oxford",
    "weightGsm": null,
    "usageTags": [
      "shirt"
    ]
  },
  {
    "id": "soktas-linda-f80275-12",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Linda Linen F80275/12",
    "composition": "",
    "colorName": "",
    "patternName": "Dobby designs",
    "constructionName": "Cotton-Linen",
    "weightGsm": null,
    "usageTags": [
      "shirt",
      "summer shirt"
    ]
  },
  {
    "id": "soktas-miami-f62585-1000",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Miami Linen F62585/1000",
    "composition": "100% Linen",
    "colorName": "",
    "patternName": "",
    "constructionName": "Linen",
    "weightGsm": null,
    "usageTags": [
      "shirt",
      "summer shirt"
    ]
  },
  {
    "id": "soktas-palm-beach-f91777-01",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Palm Beach F91777/01",
    "composition": "100% Linen",
    "colorName": "",
    "patternName": "",
    "constructionName": "Linen",
    "weightGsm": null,
    "usageTags": [
      "shirt",
      "summer shirt"
    ]
  },
  {
    "id": "soktas-singapore-f92604-01",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Singapore Organic F92604/01",
    "composition": "Organic cotton",
    "colorName": "",
    "patternName": "",
    "constructionName": "",
    "weightGsm": null,
    "usageTags": [
      "shirt"
    ]
  },
  {
    "id": "soktas-wessex-f74916-01",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Wessex F74916/01",
    "composition": "",
    "colorName": "",
    "patternName": "Flannel checks",
    "constructionName": "Flannel",
    "weightGsm": null,
    "usageTags": [
      "shirt",
      "casual shirt"
    ]
  },
  {
    "id": "soktas-wessex-f74916-05",
    "sourceId": "soktas",
    "manufacturer": "SÖKTAŞ",
    "productName": "Wessex F74916/05",
    "composition": "",
    "colorName": "",
    "patternName": "Flannel checks",
    "constructionName": "Flannel",
    "weightGsm": null,
    "usageTags": [
      "shirt",
      "casual shirt"
    ]
  },
  {
    "id": "standeven-british-classic-4041",
    "sourceId": "standeven",
    "manufacturer": "Standeven Fabrics",
    "productName": "British Classic Check 4041",
    "composition": "100% Wool",
    "colorName": "Black x White",
    "patternName": "Check",
    "constructionName": "British Classic",
    "weightGsm": 360,
    "usageTags": [
      "suit"
    ]
  },
  {
    "id": "standeven-glenesk-19054",
    "sourceId": "standeven",
    "manufacturer": "Standeven Fabrics",
    "productName": "Glenesk Herringbone Windowpane Check Jacketing 19054",
    "composition": "95% Lambswool, 5% Cashmere",
    "colorName": "Medium Brown, Blue/Tan",
    "patternName": "Herringbone Windowpane Check",
    "constructionName": "Jacketing",
    "weightGsm": 320,
    "usageTags": [
      "jacket"
    ]
  },
  {
    "id": "standeven-heritage-twist-15031",
    "sourceId": "standeven",
    "manufacturer": "Standeven Fabrics",
    "productName": "Heritage Twist Herringbone 15031",
    "composition": "100% Merino Wool",
    "colorName": "Charcoal",
    "patternName": "Herringbone",
    "constructionName": "Mid Weight Suiting",
    "weightGsm": 395,
    "usageTags": [
      "suit"
    ]
  },
  {
    "id": "standeven-signature-31005",
    "sourceId": "standeven",
    "manufacturer": "Standeven Fabrics",
    "productName": "Signature Glen Check 31005",
    "composition": "100% Super 160's Wool",
    "colorName": "",
    "patternName": "Glen Check",
    "constructionName": "Signature",
    "weightGsm": 250,
    "usageTags": [
      "suit",
      "special occasion"
    ]
  },
  {
    "id": "standeven-signature-31009",
    "sourceId": "standeven",
    "manufacturer": "Standeven Fabrics",
    "productName": "Signature Herringbone Windowpane 31009",
    "composition": "100% Super 160's Wool",
    "colorName": "",
    "patternName": "Herringbone Windowpane",
    "constructionName": "Signature",
    "weightGsm": 250,
    "usageTags": [
      "suit",
      "special occasion"
    ]
  },
  {
    "id": "standeven-signature-31007",
    "sourceId": "standeven",
    "manufacturer": "Standeven Fabrics",
    "productName": "Signature Pick & Pick Windowpane 31007",
    "composition": "100% Super 160's Wool",
    "colorName": "",
    "patternName": "Pick & Pick Windowpane Check",
    "constructionName": "Signature",
    "weightGsm": 250,
    "usageTags": [
      "suit",
      "special occasion"
    ]
  },
  {
    "id": "vbc-10-712-438",
    "sourceId": "vbc",
    "manufacturer": "Vitale Barberis Canonico",
    "productName": "10.712/438",
    "composition": "100% wool",
    "colorName": "Brown",
    "patternName": "Plain",
    "constructionName": "Hopsack",
    "weightGsm": 280,
    "usageTags": [
      "sports jacket"
    ]
  },
  {
    "id": "vbc-486-562-2",
    "sourceId": "vbc",
    "manufacturer": "Vitale Barberis Canonico",
    "productName": "Ceremony 486.562/2",
    "composition": "100% wool",
    "colorName": "Grey",
    "patternName": "Herringbone",
    "constructionName": "Worsted",
    "weightGsm": 260,
    "usageTags": [
      "ceremony",
      "business suit",
      "formal occasion"
    ]
  },
  {
    "id": "vbc-486-363-1",
    "sourceId": "vbc",
    "manufacturer": "Vitale Barberis Canonico",
    "productName": "Day wear 486.363/1",
    "composition": "100% wool",
    "colorName": "Blue",
    "patternName": "Plain",
    "constructionName": "Worsted",
    "weightGsm": 260,
    "usageTags": [
      "day wear",
      "evening wear",
      "business suit"
    ]
  },
  {
    "id": "vbc-5592-101-130",
    "sourceId": "vbc",
    "manufacturer": "Vitale Barberis Canonico",
    "productName": "Day wear 5592.101/130",
    "composition": "100% wool",
    "colorName": "Grey",
    "patternName": "Bird's eye",
    "constructionName": "Worsted",
    "weightGsm": 280,
    "usageTags": [
      "day wear",
      "suit"
    ]
  }
] as const;

export const FABRIC_REFERENCE_INDEX_VERSION = "real-reference-v1" as const;

export const FABRIC_REFERENCE_COUNTS = {
  materials: REAL_MENSWEAR_MATERIAL_TERMS.length,
  patterns: REAL_MENSWEAR_PATTERN_TERMS.length,
  colors: STANDARD_COLOR_REFERENCE_TERMS.length,
  sources: FABRIC_REFERENCE_SOURCES.length,
  examples: REAL_FABRIC_REFERENCE_EXAMPLES.length,
} as const;
