import "server-only";

export const REAL_MENSWEAR_MATERIAL_TERMS = [
  "100% linen",
  "100% linen shirting",
  "170s shirting",
  "1772 Flannel",
  "21 Micron Wool",
  "3/300s yarn count",
  "6-ply",
  "all-wool suiting",
  "Australian wool",
  "Baby Alpaca",
  "bamboo-linen blend",
  "batiste",
  "Beausoleil",
  "bouclé fabric",
  "bouclé yarn",
  "Brera Sportcoat wool-silk",
  "brushed cotton",
  "camel",
  "Carnival mohair-wool",
  "cashmere",
  "Cashmere 4.0",
  "cashmere cloth",
  "Cashmere Fleece",
  "Cashmerello",
  "Cassimere twill",
  "Chinese silk",
  "Classic Flannel",
  "coating cloth",
  "colored nepps",
  "combed long-staple cotton",
  "common twill",
  "corduroy",
  "corduroy cotton",
  "cotton",
  "cotton gabardine",
  "cotton poplin",
  "cotton tricotine",
  "cotton-linen",
  "cotton-linen shirting",
  "cotton-silk shirting",
  "covert",
  "covert cloth",
  "délavé linen",
  "Double",
  "easy-care finish",
  "Egyptian Giza 45 cotton",
  "Egyptian Giza 87 cotton",
  "Escorial wool",
  "European flax linen",
  "extra-fine worsted wool",
  "extra-long-staple cotton",
  "felted fabric",
  "flannel cloth",
  "flannel shirting",
  "flat cotton",
  "Fox Air",
  "Fox City",
  "Fox Jacketing",
  "Fox Khaki",
  "Fox Linen",
  "Fox Lining",
  "Fox Tweed",
  "Functional Fabrics",
  "Golden Fox",
  "GREENHILLS Super 180s",
  "greige raw fabric",
  "handwoven tweed",
  "Harris Tweed",
  "heavy Oxford",
  "heavy twill",
  "herringbone semi-plain",
  "herringbone shirting",
  "high-end natural fabric",
  "high-end natural fabrics",
  "hopsack",
  "indigo yarn fabric",
  "Irish linen",
  "jacketing cloth",
  "jacketing fabric",
  "jacquard",
  "jacquard fabric",
  "jacquard linen",
  "jacquard shirting",
  "jersey fabric",
  "Kid Cashmere",
  "Kid Wool 12.8",
  "Knit Icons",
  "knit-look fabric",
  "lightweight casual fabric",
  "linen",
  "Linen and the Gang",
  "linen fabric",
  "linen shirting",
  "llama",
  "London Shrunk finish",
  "long-staple cotton",
  "Machine Washable",
  "madras linen",
  "Marcella pique",
  "melange fabric",
  "melange linen",
  "Merino wool suiting",
  "mohair",
  "mohair cloth",
  "moleskin",
  "moleskin cotton",
  "Mongolian cashmere",
  "mouliné yarn",
  "natural recycled fibre fabric",
  "Natural Stretch",
  "natural-dyed fabric",
  "natural-flexibility wool",
  "Ne 100/2",
  "Ne 120/2",
  "Ne 170/2",
  "Ne 240/2",
  "Ne 80/2",
  "New Zealand wool",
  "non-iron finish",
  "non-iron sateen",
  "non-iron twill",
  "Oasi Cashmere",
  "Oasi Lino",
  "organic cotton",
  "organzine yarn",
  "overchecked linen",
  "overcoating",
  "Oxford",
  "Oxford shirting",
  "Panama design",
  "Panama weave",
  "Perennial",
  "piece-dyed seersucker",
  "pinpoint shirting",
  "polo Oxford",
  "poplin",
  "poplin shirting",
  "Precious Fabrics",
  "printed fabric",
  "printed shirting",
  "pure silk",
  "pure virgin wool",
  "pure wool cloth",
  "regenerative cotton",
  "Revenge Super 150s",
  "Royal Oxford",
  "Royal Plume fancy suiting",
  "Royal Twill",
  "Rustic Tropical",
  "Sartoria Ceremony",
  "Sartoria Contemporary",
  "Sartoria Timeless",
  "Sartoria White & Colors",
  "sateen shirting",
  "Saxon Merino Wool",
  "Saxony",
  "Sea Island cotton",
  "seersucker effect",
  "silk",
  "silk cloth",
  "silk fabric",
  "single-ply cotton yarn",
  "Skyfall 14.5 micron",
  "Skyfall Velvet",
  "Solaro Made in Italy",
  "Somerset Jacketing",
  "South African mohair",
  "Soyella",
  "Sports Jacketing",
  "spray-dyed fabric",
  "Spring 4-ply",
  "spun silk",
  "stretch fabric",
  "stretch shirting",
  "striped linen",
  "suiting cloth",
  "suiting fabric",
  "summer tailoring cloth",
  "Super 130s wool",
  "Super 140s wool",
  "Super 210s wool",
  "Super 230s wool",
  "Superbio",
  "superfine wool",
  "Superior",
  "Supima cotton",
  "Supraluxe",
  "Swing Natural B Stretch",
  "The Mohair Affair",
  "travel suiting",
  "Traveller shirting",
  "tropical",
  "Tropical Worsted",
  "tweed",
  "twill",
  "twill shirting",
  "Twill Soprano",
  "two and two twill",
  "two-ply cotton yarn",
  "undyed fabric",
  "velvet",
  "velvet cotton",
  "vicuña",
  "viscose-acetate lining",
  "voile",
  "Voyage",
  "water-and-stain-repellent wool",
  "wool",
  "Wool & Mohair",
  "wool-cashmere-mohair blend",
  "wool-cotton blend",
  "woollen",
  "woollen flannel",
  "worsted",
  "Worsted Classics",
  "worsted flannel",
  "Yangir",
  "yarn-dyed linen",
  "yarn-dyed seersucker",
  "yarn-dyed shirting",
  "Zephir"
] as const;

export const REAL_MENSWEAR_PATTERN_TERMS = [
  "2 x 1 Oxford weave",
  "2 x 1 twill",
  "2 x 2 basket weave",
  "2 x 2 twill",
  "Barathea",
  "Barley Corn",
  "Barlycorn Herringbone with Windowpane Check",
  "Bedford cord",
  "Bird's eye",
  "birdseye",
  "Bold stripe",
  "Bold Windowpane",
  "boucle",
  "bouclé effect",
  "British checks and plains",
  "Brushed twill",
  "Camouflage",
  "chain stripe",
  "Chalk stripe",
  "check",
  "Check Structured",
  "Chevron weave",
  "Classic checks",
  "Classic stripes",
  "Clip-spot",
  "colored nepp effect",
  "common twill",
  "corduroy",
  "Country check",
  "Dobby",
  "Dobby geometric",
  "Earthy plains",
  "End-on-end",
  "false plain",
  "Fancy Check",
  "Fancy Herringbone",
  "Fancy suiting",
  "Flannel checks",
  "gabardine",
  "Glen check",
  "Glen Check with Guarded Check",
  "Glen Check with Windowpane Overcheck",
  "Gunclub Check with Windowpane Check",
  "Heavy waffle weave pique",
  "herringbone",
  "herringbone semi-plain",
  "hopsack",
  "hopsack check",
  "Hopsack cloth",
  "jacquard",
  "Jacquard large repeat",
  "jacquard pattern",
  "jersey",
  "left-hand twill",
  "Leno mesh",
  "Light Panama",
  "madras",
  "marle",
  "melange",
  "Melange checks",
  "Mesh",
  "micro design",
  "micro jacquard effect",
  "micro pattern",
  "Micro Weave",
  "Micro-design",
  "moleskin",
  "mouliné effect",
  "mouline twill",
  "overcheck",
  "Oxford",
  "Panama designs",
  "Pattern stripe dobby",
  "Pencil stripe",
  "Pick and Pick",
  "pick-and-pick",
  "pin head",
  "pin stripe",
  "Pindot",
  "poplin",
  "Poplin stripes",
  "Prince of Wales",
  "Prince of Wales checks",
  "print",
  "printed pattern",
  "raw weave structure",
  "Reverse Twill Dobby",
  "right-hand twill",
  "rope stripe",
  "Royal Oxford checks",
  "Royal Oxford stripes",
  "Seersucker effect",
  "semi plain",
  "shadow stripe",
  "Shepherd Check",
  "Small check",
  "Solid Plain Structured",
  "Spot weave",
  "spray-dyed design",
  "Stitch Stripe",
  "stripe",
  "Tartan check",
  "Traditional tweed",
  "Tropical weave",
  "twill",
  "Twill checks",
  "two and two twill",
  "Two Tone Narrow Herringbone",
  "Two Tone Twill",
  "Two Tone Wide Herringbone",
  "Two Tone Windowpane Herringbone",
  "velvet",
  "velvet surface",
  "Vintage Twist Herringbone",
  "Weather-resistant plain weave",
  "Weft-way stripe",
  "White-on-white",
  "wide pinstripe",
  "Wild Herringbone Dobby",
  "windowpane",
  "Windowpane Herringbone",
  "yarn-dyed",
  "yarn-dyed pattern",
  "yarn-dyed stripe",
  "Zephyr"
] as const;

export const STANDARD_COLOR_REFERENCE_TERMS = [
  "black",
  "blackish blue",
  "blackish green",
  "blackish purple",
  "blackish red",
  "bluish black",
  "bluish gray",
  "bluish white",
  "brilliant blue",
  "brilliant bluish green",
  "brilliant green",
  "brilliant greenish blue",
  "brilliant greenish yellow",
  "brilliant orange",
  "brilliant orange yellow",
  "brilliant purple",
  "brilliant purplish blue",
  "brilliant purplish pink",
  "brilliant violet",
  "brilliant yellow",
  "brilliant yellow green",
  "brilliant yellowish green",
  "brownish black",
  "brownish gray",
  "brownish orange",
  "brownish pink",
  "dark blue",
  "dark bluish gray",
  "dark bluish green",
  "dark brown",
  "dark gray",
  "dark grayish blue",
  "dark grayish brown",
  "dark grayish green",
  "dark grayish olive",
  "dark grayish olive green",
  "dark grayish purple",
  "dark grayish red",
  "dark grayish reddish brown",
  "dark grayish yellow",
  "dark grayish yellow brown",
  "dark green",
  "dark greenish blue",
  "dark greenish gray",
  "dark greenish yellow",
  "dark olive",
  "dark olive brown",
  "dark olive green",
  "dark orange yellow",
  "dark pink",
  "dark purple",
  "dark purplish blue",
  "dark purplish gray",
  "dark purplish pink",
  "dark purplish red",
  "dark red",
  "dark reddish brown",
  "dark reddish gray",
  "dark reddish orange",
  "dark reddish purple",
  "dark violet",
  "dark yellow",
  "dark yellowish brown",
  "dark yellowish green",
  "dark yellowish pink",
  "deep blue",
  "deep bluish green",
  "deep brown",
  "deep green",
  "deep greenish blue",
  "deep greenish yellow",
  "deep olive green",
  "deep orange",
  "deep orange yellow",
  "deep pink",
  "deep purple",
  "deep purplish blue",
  "deep purplish pink",
  "deep purplish red",
  "deep red",
  "deep reddish brown",
  "deep reddish orange",
  "deep reddish purple",
  "deep violet",
  "deep yellow",
  "deep yellow green",
  "deep yellowish brown",
  "deep yellowish green",
  "deep yellowish pink",
  "grayish blue",
  "grayish brown",
  "grayish green",
  "grayish greenish yellow",
  "grayish olive",
  "grayish olive green",
  "grayish pink",
  "grayish purple",
  "grayish purplish blue",
  "grayish purplish pink",
  "grayish purplish red",
  "grayish red",
  "grayish reddish brown",
  "grayish reddish orange",
  "grayish reddish purple",
  "grayish violet",
  "grayish yellow",
  "grayish yellow green",
  "grayish yellowish brown",
  "grayish yellowish pink",
  "greenish black",
  "greenish gray",
  "greenish white",
  "light blue",
  "light bluish gray",
  "light bluish green",
  "light brown",
  "light brownish gray",
  "light gray",
  "light grayish brown",
  "light grayish olive",
  "light grayish purplish red",
  "light grayish red",
  "light grayish reddish brown",
  "light grayish yellowish brown",
  "light green",
  "light greenish blue",
  "light greenish gray",
  "light greenish yellow",
  "light olive",
  "light olive brown",
  "light olive gray",
  "light orange",
  "light orange yellow",
  "light pink",
  "light purple",
  "light purplish blue",
  "light purplish gray",
  "light purplish pink",
  "light reddish brown",
  "light reddish purple",
  "light violet",
  "light yellow",
  "light yellow green",
  "light yellowish brown",
  "light yellowish green",
  "light yellowish pink",
  "medium gray",
  "moderate blue",
  "moderate bluish green",
  "moderate brown",
  "moderate green",
  "moderate greenish blue",
  "moderate greenish yellow",
  "moderate olive",
  "moderate olive brown",
  "moderate olive green",
  "moderate orange",
  "moderate orange yellow",
  "moderate pink",
  "moderate purple",
  "moderate purplish blue",
  "moderate purplish pink",
  "moderate purplish red",
  "moderate red",
  "moderate reddish brown",
  "moderate reddish orange",
  "moderate reddish purple",
  "moderate violet",
  "moderate yellow",
  "moderate yellow green",
  "moderate yellowish brown",
  "moderate yellowish green",
  "moderate yellowish pink",
  "olive black",
  "olive gray",
  "pale blue",
  "pale green",
  "pale greenish yellow",
  "pale orange yellow",
  "pale pink",
  "pale purple",
  "pale purplish blue",
  "pale purplish pink",
  "pale reddish purple",
  "pale violet",
  "pale yellow",
  "pale yellow green",
  "pale yellowish pink",
  "pinkish gray",
  "pinkish white",
  "purplish black",
  "purplish gray",
  "purplish white",
  "reddish black",
  "reddish gray",
  "strong blue",
  "strong bluish green",
  "strong brown",
  "strong green",
  "strong greenish blue",
  "strong greenish yellow",
  "strong olive green",
  "strong orange",
  "strong orange yellow",
  "strong pink",
  "strong purple",
  "strong purplish blue",
  "strong purplish pink",
  "strong purplish red",
  "strong red",
  "strong reddish brown",
  "strong reddish orange",
  "strong reddish purple",
  "strong violet",
  "strong yellow",
  "strong yellow green",
  "strong yellowish brown",
  "strong yellowish green",
  "strong yellowish pink",
  "very dark bluish green",
  "very dark green",
  "very dark greenish blue",
  "very dark purple",
  "very dark purplish red",
  "very dark red",
  "very dark reddish purple",
  "very dark yellowish green",
  "very deep purple",
  "very deep purplish red",
  "very deep red",
  "very deep reddish purple",
  "very deep yellowish green",
  "very light blue",
  "very light bluish green",
  "very light green",
  "very light greenish blue",
  "very light purple",
  "very light purplish blue",
  "very light violet",
  "very light yellowish green",
  "very pale blue",
  "very pale green",
  "very pale purple",
  "very pale purplish blue",
  "very pale violet",
  "vivid blue",
  "vivid bluish green",
  "vivid green",
  "vivid greenish blue",
  "vivid greenish yellow",
  "vivid orange",
  "vivid orange yellow",
  "vivid pink",
  "vivid purple",
  "vivid purplish blue",
  "vivid purplish red",
  "vivid red",
  "vivid reddish orange",
  "vivid reddish purple",
  "vivid violet",
  "vivid yellow",
  "vivid yellow green",
  "vivid yellowish green",
  "vivid yellowish pink",
  "white",
  "yellowish gray",
  "yellowish white",
  "aliceblue",
  "antiquewhite",
  "aqua",
  "aquamarine",
  "azure",
  "beige",
  "bisque",
  "black",
  "blanchedalmond",
  "blue",
  "blueviolet",
  "brown",
  "burlywood",
  "cadetblue",
  "chartreuse",
  "chocolate",
  "coral",
  "cornflowerblue",
  "cornsilk",
  "crimson",
  "cyan",
  "darkblue",
  "darkcyan",
  "darkgoldenrod",
  "darkgray",
  "darkgreen",
  "darkgrey",
  "darkkhaki",
  "darkmagenta",
  "darkolivegreen",
  "darkorange",
  "darkorchid",
  "darkred",
  "darksalmon",
  "darkseagreen",
  "darkslateblue",
  "darkslategray",
  "darkslategrey",
  "darkturquoise",
  "darkviolet",
  "deeppink",
  "deepskyblue",
  "dimgray",
  "dimgrey",
  "dodgerblue",
  "firebrick",
  "floralwhite",
  "forestgreen",
  "fuchsia",
  "gainsboro",
  "ghostwhite",
  "gold",
  "goldenrod",
  "gray",
  "green",
  "greenyellow",
  "grey",
  "honeydew",
  "hotpink",
  "indianred",
  "indigo",
  "ivory",
  "khaki",
  "lavender",
  "lavenderblush",
  "lawngreen",
  "lemonchiffon",
  "lightblue",
  "lightcoral",
  "lightcyan",
  "lightgoldenrodyellow",
  "lightgray",
  "lightgreen",
  "lightgrey",
  "lightpink",
  "lightsalmon",
  "lightseagreen",
  "lightskyblue",
  "lightslategray",
  "lightslategrey",
  "lightsteelblue",
  "lightyellow",
  "lime",
  "limegreen",
  "linen",
  "magenta",
  "maroon",
  "mediumaquamarine",
  "mediumblue",
  "mediumorchid",
  "mediumpurple",
  "mediumseagreen",
  "mediumslateblue",
  "mediumspringgreen",
  "mediumturquoise",
  "mediumvioletred",
  "midnightblue",
  "mintcream",
  "mistyrose",
  "moccasin",
  "navajowhite",
  "navy",
  "oldlace",
  "olive",
  "olivedrab",
  "orange",
  "orangered",
  "orchid",
  "palegoldenrod",
  "palegreen",
  "paleturquoise",
  "palevioletred",
  "papayawhip",
  "peachpuff",
  "peru",
  "pink",
  "plum",
  "powderblue",
  "purple",
  "rebeccapurple",
  "red",
  "rosybrown",
  "royalblue",
  "saddlebrown",
  "salmon",
  "sandybrown",
  "seagreen",
  "seashell",
  "sienna",
  "silver",
  "skyblue",
  "slateblue",
  "slategray",
  "slategrey",
  "snow",
  "springgreen",
  "steelblue",
  "tan",
  "teal",
  "thistle",
  "tomato",
  "turquoise",
  "violet",
  "wheat",
  "white",
  "whitesmoke",
  "yellow",
  "yellowgreen"
] as const;

export const FABRIC_REFERENCE_SOURCES = [
  {
    "id": "acorn",
    "title": "Acorn Shirting Fabrics",
    "publisher": "Acorn Fabrics",
    "url": "https://www.acornfabrics.com/"
  },
  {
    "id": "albiate1830",
    "title": "Albiate 1830",
    "publisher": "Albiate 1830",
    "url": "https://www.albiate1830.com/en/profile/"
  },
  {
    "id": "albini1876",
    "title": "Albini 1876",
    "publisher": "Albini 1876",
    "url": "https://www.albini1876.com/"
  },
  {
    "id": "alumo",
    "title": "ALUMO Shirting Fabrics",
    "publisher": "ALUMO",
    "url": "https://www.alumo.ch/en/textile"
  },
  {
    "id": "ariston",
    "title": "Ariston Fabrics",
    "publisher": "Ariston",
    "url": "https://www.aristonfabrics.com/"
  },
  {
    "id": "bateman-ogden",
    "title": "Bateman & Ogden",
    "publisher": "Bateman & Ogden",
    "url": "https://www.batemanogden.co.uk/"
  },
  {
    "id": "brisbane-moss",
    "title": "Brisbane Moss",
    "publisher": "Brisbane Moss",
    "url": "https://www.brisbanemoss.co.uk/products/"
  },
  {
    "id": "caccioppoli",
    "title": "Caccioppoli Napoli",
    "publisher": "Caccioppoli Napoli",
    "url": "https://www.caccioppolinapoli.it/en/company/"
  },
  {
    "id": "canepa",
    "title": "Canepa Fabric Division",
    "publisher": "Canepa",
    "url": "https://www.canepa.it/en/products/fabric"
  },
  {
    "id": "lenzing",
    "title": "Cellulosic fiber knowledge",
    "publisher": "Lenzing",
    "url": "https://www.lenzing.com/products"
  },
  {
    "id": "cottonworks",
    "title": "Cotton textile education",
    "publisher": "CottonWorks",
    "url": "https://cottonworks.com/"
  },
  {
    "id": "w3c-css-color",
    "title": "CSS Color Module",
    "publisher": "W3C",
    "url": "https://www.w3.org/TR/css-color/"
  },
  {
    "id": "dormeuil",
    "title": "Dormeuil Fabrics",
    "publisher": "Dormeuil",
    "url": "https://dormeuil.com/collections/fabric-fabric"
  },
  {
    "id": "drago",
    "title": "Drago Lanificio in Biella",
    "publisher": "Drago",
    "url": "https://www.dragobiella.it/en/collection/"
  },
  {
    "id": "dugdale",
    "title": "Dugdale Bros & Co",
    "publisher": "Dugdale Bros & Co",
    "url": "https://www.dugdalebros.com/collections/"
  },
  {
    "id": "flaxlinenhemp",
    "title": "European flax and linen knowledge",
    "publisher": "Alliance for European Flax-Linen & Hemp",
    "url": "https://allianceflaxlinenhemp.eu/"
  },
  {
    "id": "ferla",
    "title": "Ferla",
    "publisher": "Lanificio Egidio Ferla",
    "url": "https://www.ferla.it/eng/index.php"
  },
  {
    "id": "alliance-flax",
    "title": "Flax Performance and Properties",
    "publisher": "Alliance for European Flax-Linen & Hemp",
    "url": "https://allianceflaxlinenhemp.eu/en/flax-performance-and-properties"
  },
  {
    "id": "fox-brothers",
    "title": "Fox Brothers Cloth",
    "publisher": "Fox Brothers & Co",
    "url": "https://foxflannel.com/collections/cloth-shop"
  },
  {
    "id": "tallia-delfino",
    "title": "Fratelli Tallia di Delfino",
    "publisher": "Fratelli Tallia di Delfino",
    "url": "https://www.tallia-delfino.com/"
  },
  {
    "id": "getzner",
    "title": "Getzner Textil Shirting",
    "publisher": "Getzner Textil",
    "url": "https://getznerholding.at/en/getzner-textil/"
  },
  {
    "id": "canclini",
    "title": "Grandi & Rubinelli / Canclini",
    "publisher": "Canclini",
    "url": "https://www.canclini.it/en/brands/grandi-rubinelli/collections-gr/"
  },
  {
    "id": "guabello",
    "title": "Guabello",
    "publisher": "Guabello",
    "url": "https://www.guabello.it/en/homepage/"
  },
  {
    "id": "harris-tweed-authority",
    "title": "Harris Tweed Authority",
    "publisher": "Harris Tweed Authority",
    "url": "https://www.harristweed.org/"
  },
  {
    "id": "holland-sherry",
    "title": "Holland & Sherry Apparel",
    "publisher": "Holland & Sherry",
    "url": "https://apparel.hollandandsherry.com/"
  },
  {
    "id": "huddersfield",
    "title": "Huddersfield Fine Worsteds",
    "publisher": "Huddersfield Fine Worsteds",
    "url": "https://www.hfwltd.com/"
  },
  {
    "id": "nist-iscc-nbs",
    "title": "ISCC-NBS Color: Universal Language and Dictionary of Names",
    "publisher": "National Institute of Standards and Technology",
    "url": "https://www.nist.gov/publications/color-universal-language-and-dictionary-names"
  },
  {
    "id": "carlo-barbera",
    "title": "Lanificio Carlo Barbera",
    "publisher": "Carlo Barbera",
    "url": "https://www.carlobarbera.it/en/"
  },
  {
    "id": "lanificio-colombo",
    "title": "Lanificio Colombo",
    "publisher": "Lanificio Colombo",
    "url": "https://www.lanificiocolombo.com/"
  },
  {
    "id": "cerruti",
    "title": "Lanificio F.lli Cerruti",
    "publisher": "Lanificio F.lli Cerruti",
    "url": "https://www.lanificiocerruti.com/luxury-man-collection/"
  },
  {
    "id": "subalpino",
    "title": "Lanificio Subalpino",
    "publisher": "Lanificio Subalpino",
    "url": "https://www.lanificiosubalpino.com/en/"
  },
  {
    "id": "loro-piana-textile",
    "title": "Loro Piana Textile",
    "publisher": "Loro Piana",
    "url": "https://www.loropiana.com/textile/"
  },
  {
    "id": "marlane",
    "title": "Marlane",
    "publisher": "Marlane",
    "url": "https://marlane.it/en/"
  },
  {
    "id": "marzotto",
    "title": "Marzotto Tessuti",
    "publisher": "Marzotto Wool Manufacturing",
    "url": "https://www.marzottotessuti.it/en/"
  },
  {
    "id": "hollandsherry",
    "title": "Menswear cloth reference",
    "publisher": "Holland & Sherry",
    "url": "https://www.hollandandsherry.com/"
  },
  {
    "id": "mileta",
    "title": "MILETA Shirting Fabrics",
    "publisher": "MILETA",
    "url": "https://www.mileta.cz/index_en.php?page=our-products"
  },
  {
    "id": "piacenza1733",
    "title": "Piacenza 1733 Fabrics",
    "publisher": "Piacenza 1733",
    "url": "https://fabrics.piacenza1733.com/"
  },
  {
    "id": "reda1865",
    "title": "Reda 1865",
    "publisher": "Reda",
    "url": "https://www.reda1865.com/row/"
  },
  {
    "id": "scabal",
    "title": "Scabal Fabrics",
    "publisher": "Scabal",
    "url": "https://scabal.com/pages/fabrics-collection-ss26"
  },
  {
    "id": "soktas",
    "title": "SÖKTAŞ Shirting Fabrics",
    "publisher": "SÖKTAŞ",
    "url": "https://shop.soktas.com/product-category/all-fabrics/"
  },
  {
    "id": "solbiati",
    "title": "Solbiati",
    "publisher": "Solbiati",
    "url": "https://www.solbiati.it/en/home.html"
  },
  {
    "id": "standeven",
    "title": "Standeven Fabrics",
    "publisher": "Standeven Fabrics",
    "url": "https://www.standevenfabrics.co.uk/pages/cloth"
  },
  {
    "id": "lenzing-lyocell",
    "title": "TENCEL Lyocell",
    "publisher": "Lenzing",
    "url": "https://www.lenzing.com/products/textile-fibers/tenceltm-lyocell/"
  },
  {
    "id": "lenzing-modal",
    "title": "TENCEL Modal",
    "publisher": "Lenzing",
    "url": "https://www.lenzing.com/products/textile-fibers/tenceltm-modal/"
  },
  {
    "id": "monti",
    "title": "Tessitura Monti Shirting",
    "publisher": "Tessitura Monti India",
    "url": "https://www.monti.co.in/"
  },
  {
    "id": "thomas-mason",
    "title": "Thomas Mason Shirting",
    "publisher": "Thomas Mason",
    "url": "https://www.thomasmason.co.uk/"
  },
  {
    "id": "vbc",
    "title": "Vitale Barberis Canonico Fabrics",
    "publisher": "Vitale Barberis Canonico",
    "url": "https://vitalebarberiscanonico.com/collection/fabrics/"
  },
  {
    "id": "woolmark-suiting",
    "title": "Wool Suiting",
    "publisher": "The Woolmark Company",
    "url": "https://www.woolmark.com/z.archive/archive-industry/suiting/"
  },
  {
    "id": "woolmark",
    "title": "Wool textile and apparel knowledge",
    "publisher": "The Woolmark Company",
    "url": "https://www.woolmark.com/industry/"
  },
  {
    "id": "zegna-filiera",
    "title": "Zegna Luxury Textile Laboratory",
    "publisher": "Ermenegildo Zegna Group",
    "url": "https://www.zegnagroup.com/en/our-filiera/"
  }
] as const;

export const FABRIC_REFERENCE_INDEX_VERSION = "real-reference-v2" as const;

export const FABRIC_REFERENCE_COUNTS = {
  materials: REAL_MENSWEAR_MATERIAL_TERMS.length,
  patterns: REAL_MENSWEAR_PATTERN_TERMS.length,
  colors: STANDARD_COLOR_REFERENCE_TERMS.length,
  sources: FABRIC_REFERENCE_SOURCES.length,
} as const;
