import type {
  ColorFamilyId,
  GarmentUseId,
  OccasionId,
  ClimateTagId,
  CollarOptionId,
  CuffOptionId,
  ShirtFitOptionId,
  TrouserDirectionId,
  PatternStrategyId,
} from "@/lib/vocab";

export type DesignerFabricIntelligence = {
  profileId:string;
  analyzerVersion:string;
  reviewStatus:"unreviewed"|"approved"|"corrected"|"rejected";
  trust:"reviewed"|"high-confidence"|"provisional";
  measuredEvidence:{
    imageQualityScore:number|null;
    colorDeltaE:number|null;
    measuredHex:string|null;
    patternContrastDeltaE:number|null;
    patternOrientation:"none"|"vertical"|"horizontal"|"grid"|"uncertain"|null;
    patternPhysicalScale:"declared_repeat"|"declared_swatch_width"|"unknown"|null;
    repeatMm:number|null;
    stripeWidthMm:number|null;
    contentSha256:string|null;
  };
  verifiedPhysical:{
    gsm:number|null;
    drape:"Fluid"|"Balanced"|"Structured"|null;
    fiberContent:string|null;
    sourceUrl:string|null;
  };
  fieldProvenance?:Record<string,"measured"|"modelJudged"|"declared"|"reviewed">;
  colorFamily:ColorFamilyId|null;
  undertone:"warm"|"cool"|"neutral"|"uncertain";
  depth:"very-light"|"light"|"mid"|"deep"|"very-deep";
  saturation:"muted"|"soft"|"medium"|"rich"|"vivid";
  patternFamily:"solid"|"stripe"|"check"|"dot"|"botanical"|"floral"|"geometric"|"paisley"|"abstract"|"melange"|"textured"|"other";
  patternScale:"none"|"fine"|"medium"|"bold";
  patternDensity:"none"|"sparse"|"balanced"|"dense";
  patternContrast:"low"|"medium"|"high";
  visibleTexture:string[];
  weaveAppearance:string[];
  sheen:"matte"|"low"|"medium"|"high"|"uncertain";
  visualWeight:"light-looking"|"medium-looking"|"heavy-looking"|"uncertain";
  personality:string[];
  formality:1|2|3|4|5;
  statementLevel:1|2|3|4|5;
  bestGarments:GarmentUseId[];
  bestOccasions:OccasionId[];
  climateVisualFit:ClimateTagId[];
  recommendedConstruction:{
    collars:CollarOptionId[];
    cuffs:CuffOptionId[];
    shirtFits:ShirtFitOptionId[];
    trouserDirections:TrouserDirectionId[];
  };
  pairing:{
    goodColorFamilies:ColorFamilyId[];
    avoidColorFamilies:ColorFamilyId[];
    goodPatternStrategy:PatternStrategyId[];
  };
  reviewNeeded:string[];
  confidence:{
    color:number;
    pattern:number;
    texture:number;
    styling:number;
  };
  references:{
    materialTerms:string[];
    patternTerms:string[];
    colorTerms:string[];
    sourceIds:string[];
  };
};

export function fabricIntelligenceConfidence(value:DesignerFabricIntelligence) {
  return (value.confidence.color+value.confidence.pattern+value.confidence.texture+value.confidence.styling)/4;
}
