import type { FabricColorway } from "@/lib/fabric-stock";

/**
 * 91 swatches discovered from LLinen Earth's existing public product galleries.
 * They are included in operator inventory as unverified website stock and are not
 * automatically used by Style Director until the operator confirms them.
 */
export const LEGACY_WEBSITE_STOCK: FabricColorway[] = [
  {
    id: "legacy-60lea-plain-img-5369",
    family: "Linen",
    line: "60 Lea Plain · Legacy Website",
    colorName: "60 Lea Plain · IMG_5369",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-plain/IMG_5369.JPG",
    suitableFor: ["shirt"],
    pattern: "Plain",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 1,
    inStock: false,
  },
  {
    id: "legacy-60lea-plain-img-5372",
    family: "Linen",
    line: "60 Lea Plain · Legacy Website",
    colorName: "60 Lea Plain · IMG_5372",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-plain/IMG_5372.JPG",
    suitableFor: ["shirt"],
    pattern: "Plain",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 2,
    inStock: false,
  },
  {
    id: "legacy-60lea-plain-img-5374",
    family: "Linen",
    line: "60 Lea Plain · Legacy Website",
    colorName: "60 Lea Plain · IMG_5374",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-plain/IMG_5374.JPG",
    suitableFor: ["shirt"],
    pattern: "Plain",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 3,
    inStock: false,
  },
  {
    id: "legacy-60lea-plain-img-5376",
    family: "Linen",
    line: "60 Lea Plain · Legacy Website",
    colorName: "60 Lea Plain · IMG_5376",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-plain/IMG_5376.JPG",
    suitableFor: ["shirt"],
    pattern: "Plain",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 4,
    inStock: false,
  },
  {
    id: "legacy-60lea-plain-img-5378",
    family: "Linen",
    line: "60 Lea Plain · Legacy Website",
    colorName: "60 Lea Plain · IMG_5378",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-plain/IMG_5378.JPG",
    suitableFor: ["shirt"],
    pattern: "Plain",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 5,
    inStock: false,
  },
  {
    id: "legacy-60lea-plain-img-5379",
    family: "Linen",
    line: "60 Lea Plain · Legacy Website",
    colorName: "60 Lea Plain · IMG_5379",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-plain/IMG_5379.JPG",
    suitableFor: ["shirt"],
    pattern: "Plain",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 6,
    inStock: false,
  },
  {
    id: "legacy-60lea-formals-img-5479",
    family: "Linen",
    line: "60 Lea Formals · Legacy Website",
    colorName: "60 Lea Formals · IMG_5479",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-formals/IMG_5479.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 1,
    inStock: false,
  },
  {
    id: "legacy-60lea-formals-img-5489",
    family: "Linen",
    line: "60 Lea Formals · Legacy Website",
    colorName: "60 Lea Formals · IMG_5489",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-formals/IMG_5489.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 2,
    inStock: false,
  },
  {
    id: "legacy-60lea-formals-img-5490",
    family: "Linen",
    line: "60 Lea Formals · Legacy Website",
    colorName: "60 Lea Formals · IMG_5490",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-formals/IMG_5490.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 3,
    inStock: false,
  },
  {
    id: "legacy-60lea-formals-img-5494",
    family: "Linen",
    line: "60 Lea Formals · Legacy Website",
    colorName: "60 Lea Formals · IMG_5494",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-formals/IMG_5494.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 4,
    inStock: false,
  },
  {
    id: "legacy-60lea-formals-img-5503",
    family: "Linen",
    line: "60 Lea Formals · Legacy Website",
    colorName: "60 Lea Formals · IMG_5503",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-formals/IMG_5503.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 5,
    inStock: false,
  },
  {
    id: "legacy-60lea-formals-img-5511",
    family: "Linen",
    line: "60 Lea Formals · Legacy Website",
    colorName: "60 Lea Formals · IMG_5511",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-formals/IMG_5511.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 6,
    inStock: false,
  },
  {
    id: "legacy-60lea-formals-img-5523",
    family: "Linen",
    line: "60 Lea Formals · Legacy Website",
    colorName: "60 Lea Formals · IMG_5523",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-formals/IMG_5523.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 7,
    inStock: false,
  },
  {
    id: "legacy-60lea-formals-img-5525",
    family: "Linen",
    line: "60 Lea Formals · Legacy Website",
    colorName: "60 Lea Formals · IMG_5525",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-formals/IMG_5525.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 8,
    inStock: false,
  },
  {
    id: "legacy-60lea-formals-img-5543",
    family: "Linen",
    line: "60 Lea Formals · Legacy Website",
    colorName: "60 Lea Formals · IMG_5543",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-formals/IMG_5543.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 9,
    inStock: false,
  },
  {
    id: "legacy-60lea-formals-img-5553",
    family: "Linen",
    line: "60 Lea Formals · Legacy Website",
    colorName: "60 Lea Formals · IMG_5553",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-formals/IMG_5553.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 10,
    inStock: false,
  },
  {
    id: "legacy-60lea-formals-img-5554",
    family: "Linen",
    line: "60 Lea Formals · Legacy Website",
    colorName: "60 Lea Formals · IMG_5554",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-formals/IMG_5554.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 11,
    inStock: false,
  },
  {
    id: "legacy-60lea-formals-img-5558",
    family: "Linen",
    line: "60 Lea Formals · Legacy Website",
    colorName: "60 Lea Formals · IMG_5558",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/60lea-formals/IMG_5558.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 12,
    inStock: false,
  },
  {
    id: "legacy-75lea-formals-img-5147",
    family: "Linen",
    line: "75 Lea Formals · Legacy Website",
    colorName: "75 Lea Formals · IMG_5147",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/75-lea-formals/IMG_5147.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 1,
    inStock: false,
  },
  {
    id: "legacy-75lea-formals-img-5148",
    family: "Linen",
    line: "75 Lea Formals · Legacy Website",
    colorName: "75 Lea Formals · IMG_5148",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/75-lea-formals/IMG_5148.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 2,
    inStock: false,
  },
  {
    id: "legacy-75lea-formals-img-5155",
    family: "Linen",
    line: "75 Lea Formals · Legacy Website",
    colorName: "75 Lea Formals · IMG_5155",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/75-lea-formals/IMG_5155.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 3,
    inStock: false,
  },
  {
    id: "legacy-75lea-formals-img-5156",
    family: "Linen",
    line: "75 Lea Formals · Legacy Website",
    colorName: "75 Lea Formals · IMG_5156",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/75-lea-formals/IMG_5156.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 4,
    inStock: false,
  },
  {
    id: "legacy-75lea-formals-img-5203",
    family: "Linen",
    line: "75 Lea Formals · Legacy Website",
    colorName: "75 Lea Formals · IMG_5203",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/75-lea-formals/IMG_5203.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 5,
    inStock: false,
  },
  {
    id: "legacy-75lea-formals-img-5206",
    family: "Linen",
    line: "75 Lea Formals · Legacy Website",
    colorName: "75 Lea Formals · IMG_5206",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/75-lea-formals/IMG_5206.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 6,
    inStock: false,
  },
  {
    id: "legacy-75lea-formals-img-5214",
    family: "Linen",
    line: "75 Lea Formals · Legacy Website",
    colorName: "75 Lea Formals · IMG_5214",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/75-lea-formals/IMG_5214.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 7,
    inStock: false,
  },
  {
    id: "legacy-75lea-formals-img-5287",
    family: "Linen",
    line: "75 Lea Formals · Legacy Website",
    colorName: "75 Lea Formals · IMG_5287",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/75-lea-formals/IMG_5287.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 8,
    inStock: false,
  },
  {
    id: "legacy-75lea-formals-img-5296",
    family: "Linen",
    line: "75 Lea Formals · Legacy Website",
    colorName: "75 Lea Formals · IMG_5296",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/75-lea-formals/IMG_5296.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 9,
    inStock: false,
  },
  {
    id: "legacy-75lea-formals-img-5298",
    family: "Linen",
    line: "75 Lea Formals · Legacy Website",
    colorName: "75 Lea Formals · IMG_5298",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/75-lea-formals/IMG_5298.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 10,
    inStock: false,
  },
  {
    id: "legacy-75lea-formals-img-5301",
    family: "Linen",
    line: "75 Lea Formals · Legacy Website",
    colorName: "75 Lea Formals · IMG_5301",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/75-lea-formals/IMG_5301.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 11,
    inStock: false,
  },
  {
    id: "legacy-75lea-formals-img-5318",
    family: "Linen",
    line: "75 Lea Formals · Legacy Website",
    colorName: "75 Lea Formals · IMG_5318",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/75-lea-formals/IMG_5318.JPG",
    suitableFor: ["shirt"],
    pattern: "Formal weave / pattern",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 12,
    inStock: false,
  },
  {
    id: "legacy-cotton-plain-img-5994",
    family: "Cotton",
    line: "Cotton Plain · Legacy Website",
    colorName: "Cotton Plain · IMG_5994",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-plain/IMG_5994.JPG",
    suitableFor: ["shirt"],
    pattern: "Plain",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 1,
    inStock: false,
  },
  {
    id: "legacy-cotton-plain-img-5996",
    family: "Cotton",
    line: "Cotton Plain · Legacy Website",
    colorName: "Cotton Plain · IMG_5996",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-plain/IMG_5996.JPG",
    suitableFor: ["shirt"],
    pattern: "Plain",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 2,
    inStock: false,
  },
  {
    id: "legacy-cotton-plain-img-5997",
    family: "Cotton",
    line: "Cotton Plain · Legacy Website",
    colorName: "Cotton Plain · IMG_5997",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-plain/IMG_5997.JPG",
    suitableFor: ["shirt"],
    pattern: "Plain",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 3,
    inStock: false,
  },
  {
    id: "legacy-cotton-plain-img-5998",
    family: "Cotton",
    line: "Cotton Plain · Legacy Website",
    colorName: "Cotton Plain · IMG_5998",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-plain/IMG_5998.JPG",
    suitableFor: ["shirt"],
    pattern: "Plain",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 4,
    inStock: false,
  },
  {
    id: "legacy-cotton-plain-img-6001",
    family: "Cotton",
    line: "Cotton Plain · Legacy Website",
    colorName: "Cotton Plain · IMG_6001",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-plain/IMG_6001.JPG",
    suitableFor: ["shirt"],
    pattern: "Plain",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 5,
    inStock: false,
  },
  {
    id: "legacy-cotton-plain-img-6002",
    family: "Cotton",
    line: "Cotton Plain · Legacy Website",
    colorName: "Cotton Plain · IMG_6002",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-plain/IMG_6002.JPG",
    suitableFor: ["shirt"],
    pattern: "Plain",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 6,
    inStock: false,
  },
  {
    id: "legacy-cotton-print-img-5676",
    family: "Cotton",
    line: "Cotton Print · Legacy Website",
    colorName: "Cotton Print · IMG_5676",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-print/IMG_5676.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 1,
    inStock: false,
  },
  {
    id: "legacy-cotton-print-img-5687",
    family: "Cotton",
    line: "Cotton Print · Legacy Website",
    colorName: "Cotton Print · IMG_5687",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-print/IMG_5687.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 2,
    inStock: false,
  },
  {
    id: "legacy-cotton-print-img-5688",
    family: "Cotton",
    line: "Cotton Print · Legacy Website",
    colorName: "Cotton Print · IMG_5688",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-print/IMG_5688.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 3,
    inStock: false,
  },
  {
    id: "legacy-cotton-print-img-5690",
    family: "Cotton",
    line: "Cotton Print · Legacy Website",
    colorName: "Cotton Print · IMG_5690",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-print/IMG_5690.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 4,
    inStock: false,
  },
  {
    id: "legacy-cotton-print-img-5695",
    family: "Cotton",
    line: "Cotton Print · Legacy Website",
    colorName: "Cotton Print · IMG_5695",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-print/IMG_5695.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 5,
    inStock: false,
  },
  {
    id: "legacy-cotton-print-img-5712",
    family: "Cotton",
    line: "Cotton Print · Legacy Website",
    colorName: "Cotton Print · IMG_5712",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-print/IMG_5712.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 6,
    inStock: false,
  },
  {
    id: "legacy-cotton-print-img-5723",
    family: "Cotton",
    line: "Cotton Print · Legacy Website",
    colorName: "Cotton Print · IMG_5723",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-print/IMG_5723.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 7,
    inStock: false,
  },
  {
    id: "legacy-cotton-print-img-5724",
    family: "Cotton",
    line: "Cotton Print · Legacy Website",
    colorName: "Cotton Print · IMG_5724",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-print/IMG_5724.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 8,
    inStock: false,
  },
  {
    id: "legacy-cotton-print-img-5732",
    family: "Cotton",
    line: "Cotton Print · Legacy Website",
    colorName: "Cotton Print · IMG_5732",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-print/IMG_5732.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 9,
    inStock: false,
  },
  {
    id: "legacy-cotton-print-img-5735",
    family: "Cotton",
    line: "Cotton Print · Legacy Website",
    colorName: "Cotton Print · IMG_5735",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-print/IMG_5735.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 10,
    inStock: false,
  },
  {
    id: "legacy-cotton-print-img-5738",
    family: "Cotton",
    line: "Cotton Print · Legacy Website",
    colorName: "Cotton Print · IMG_5738",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-print/IMG_5738.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 11,
    inStock: false,
  },
  {
    id: "legacy-cotton-print-img-5759",
    family: "Cotton",
    line: "Cotton Print · Legacy Website",
    colorName: "Cotton Print · IMG_5759",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-print/IMG_5759.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 12,
    inStock: false,
  },
  {
    id: "legacy-cotton-print-img-5760",
    family: "Cotton",
    line: "Cotton Print · Legacy Website",
    colorName: "Cotton Print · IMG_5760",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-print/IMG_5760.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 13,
    inStock: false,
  },
  {
    id: "legacy-cotton-print-img-5763",
    family: "Cotton",
    line: "Cotton Print · Legacy Website",
    colorName: "Cotton Print · IMG_5763",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/cotton-print/IMG_5763.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 14,
    inStock: false,
  },
  {
    id: "legacy-digital-print-img-5075",
    family: "Digital Print",
    line: "Digital Print · Legacy Website",
    colorName: "Digital Print · IMG_5075",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/digital-print/IMG_5075.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 1,
    inStock: false,
  },
  {
    id: "legacy-digital-print-img-5078",
    family: "Digital Print",
    line: "Digital Print · Legacy Website",
    colorName: "Digital Print · IMG_5078",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/digital-print/IMG_5078.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 2,
    inStock: false,
  },
  {
    id: "legacy-digital-print-img-5079",
    family: "Digital Print",
    line: "Digital Print · Legacy Website",
    colorName: "Digital Print · IMG_5079",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/digital-print/IMG_5079.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 3,
    inStock: false,
  },
  {
    id: "legacy-digital-print-img-5087",
    family: "Digital Print",
    line: "Digital Print · Legacy Website",
    colorName: "Digital Print · IMG_5087",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/digital-print/IMG_5087.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 4,
    inStock: false,
  },
  {
    id: "legacy-digital-print-img-5093",
    family: "Digital Print",
    line: "Digital Print · Legacy Website",
    colorName: "Digital Print · IMG_5093",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/digital-print/IMG_5093.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 5,
    inStock: false,
  },
  {
    id: "legacy-digital-print-img-5096",
    family: "Digital Print",
    line: "Digital Print · Legacy Website",
    colorName: "Digital Print · IMG_5096",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/digital-print/IMG_5096.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 6,
    inStock: false,
  },
  {
    id: "legacy-digital-print-img-5120",
    family: "Digital Print",
    line: "Digital Print · Legacy Website",
    colorName: "Digital Print · IMG_5120",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/digital-print/IMG_5120.JPG",
    suitableFor: ["shirt"],
    pattern: "Print",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 7,
    inStock: false,
  },
  {
    id: "legacy-linen-suiting-img-5570",
    family: "Linen",
    line: "Linen Suiting · Legacy Website",
    colorName: "Linen Suiting · IMG_5570",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/linen-suiting/IMG_5570.JPG",
    suitableFor: ["trouser", "suit", "blazer"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 1,
    inStock: false,
  },
  {
    id: "legacy-linen-suiting-img-5573",
    family: "Linen",
    line: "Linen Suiting · Legacy Website",
    colorName: "Linen Suiting · IMG_5573",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/linen-suiting/IMG_5573.JPG",
    suitableFor: ["trouser", "suit", "blazer"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 2,
    inStock: false,
  },
  {
    id: "legacy-linen-suiting-img-5575",
    family: "Linen",
    line: "Linen Suiting · Legacy Website",
    colorName: "Linen Suiting · IMG_5575",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/linen-suiting/IMG_5575.JPG",
    suitableFor: ["trouser", "suit", "blazer"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 3,
    inStock: false,
  },
  {
    id: "legacy-linen-suiting-img-5583",
    family: "Linen",
    line: "Linen Suiting · Legacy Website",
    colorName: "Linen Suiting · IMG_5583",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/linen-suiting/IMG_5583.JPG",
    suitableFor: ["trouser", "suit", "blazer"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 4,
    inStock: false,
  },
  {
    id: "legacy-linen-suiting-img-5594",
    family: "Linen",
    line: "Linen Suiting · Legacy Website",
    colorName: "Linen Suiting · IMG_5594",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/linen-suiting/IMG_5594.JPG",
    suitableFor: ["trouser", "suit", "blazer"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 5,
    inStock: false,
  },
  {
    id: "legacy-linen-suiting-img-5599",
    family: "Linen",
    line: "Linen Suiting · Legacy Website",
    colorName: "Linen Suiting · IMG_5599",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/linen-suiting/IMG_5599.JPG",
    suitableFor: ["trouser", "suit", "blazer"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 6,
    inStock: false,
  },
  {
    id: "legacy-linen-suiting-img-5602",
    family: "Linen",
    line: "Linen Suiting · Legacy Website",
    colorName: "Linen Suiting · IMG_5602",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/linen-suiting/IMG_5602.JPG",
    suitableFor: ["trouser", "suit", "blazer"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 7,
    inStock: false,
  },
  {
    id: "legacy-linen-suiting-img-5619",
    family: "Linen",
    line: "Linen Suiting · Legacy Website",
    colorName: "Linen Suiting · IMG_5619",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/linen-suiting/IMG_5619.JPG",
    suitableFor: ["trouser", "suit", "blazer"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 8,
    inStock: false,
  },
  {
    id: "legacy-linen-suiting-img-5622",
    family: "Linen",
    line: "Linen Suiting · Legacy Website",
    colorName: "Linen Suiting · IMG_5622",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/linen-suiting/IMG_5622.JPG",
    suitableFor: ["trouser", "suit", "blazer"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 9,
    inStock: false,
  },
  {
    id: "legacy-linen-suiting-img-5636",
    family: "Linen",
    line: "Linen Suiting · Legacy Website",
    colorName: "Linen Suiting · IMG_5636",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/linen-suiting/IMG_5636.JPG",
    suitableFor: ["trouser", "suit", "blazer"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 10,
    inStock: false,
  },
  {
    id: "legacy-linen-suiting-img-5674",
    family: "Linen",
    line: "Linen Suiting · Legacy Website",
    colorName: "Linen Suiting · IMG_5674",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/linen-suiting/IMG_5674.JPG",
    suitableFor: ["trouser", "suit", "blazer"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 11,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5809",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5809",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5809.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 1,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5814",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5814",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5814.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 2,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5821",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5821",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5821.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 3,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5825",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5825",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5825.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 4,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5842",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5842",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5842.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 5,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5844",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5844",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5844.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 6,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5846",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5846",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5846.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 7,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5849",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5849",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5849.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 8,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5850",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5850",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5850.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 9,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5856",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5856",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5856.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 10,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5870",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5870",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5870.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 11,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5894",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5894",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5894.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 12,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5900",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5900",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5900.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 13,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5921",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5921",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5921.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 14,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5922",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5922",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5922.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 15,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5926",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5926",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5926.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 16,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5930",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5930",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5930.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 17,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5935",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5935",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5935.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 18,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5941",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5941",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5941.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 19,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5943",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5943",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5943.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 20,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5946",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5946",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5946.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 21,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5979",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5979",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5979.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 22,
    inStock: false,
  },
  {
    id: "legacy-luxurious-cotton-img-5984",
    family: "Cotton",
    line: "Luxurious Cotton · Legacy Website",
    colorName: "Luxurious Cotton · IMG_5984",
    hex: "#8A8178",
    swatchImageUrl: "https://llinenearth.com/products/luxurious-cotton/IMG_5984.JPG",
    suitableFor: ["shirt"],
    pattern: "Website swatch",
    compositionNote: "Imported from llinenearth.com legacy gallery. Exact colour name/composition and current physical stock must be confirmed by the operator before customer-facing recommendation.",
    sourceDocument: "llinenearth.com",
    sourcePage: 23,
    inStock: false,
  }
];
