import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { knowledgeSummary } from "@/lib/knowledge";

const refs = [
  { img: "https://images.pexels.com/photos/6766385/pexels-photo-6766385.jpeg", title: "The atelier", copy: "Construction, proportion and material should read as one system." },
  { img: "https://images.pexels.com/photos/6766382/pexels-photo-6766382.jpeg", title: "Measured, not generic", copy: "The digital experience stays rooted in tailoring craft." },
  { img: "https://images.pexels.com/photos/6764999/pexels-photo-6764999.jpeg", title: "A modern menswear world", copy: "Quiet confidence rather than an AI-dashboard aesthetic." },
];

export default function Home() {
  const intelligenceCount = knowledgeSummary.garments + knowledgeSummary.fabrics + knowledgeSummary.contexts + knowledgeSummary.aesthetics;
  return <AppShell>
    <section className="hero wrap"><div><p className="eyebrow">LLINEN EARTH · THE DIGITAL ATELIER</p><h1>Begin with fabric. End with a point of view.</h1><p className="lede">Upload a fabric, define the moment, let the Designer judge what that cloth should become, compare complete directions, refine only what matters, then carry the locked design into the physical atelier.</p><div className="actions"><Link className="button light" href="/designer">Start designing</Link><Link className="button" href="/knowledge">Explore wear & fabric library</Link></div><div className="meta"><span>Fabric-aware</span><span>Occasion-aware</span><span>Human handoff</span></div></div><div className="visual"><div className="mainPhoto" style={{ backgroundImage: `linear-gradient(180deg,rgba(5,9,17,.02),rgba(5,9,17,.76)),url('${refs[0].img}')` }} /><div className="detailPhoto" style={{ backgroundImage: `linear-gradient(180deg,rgba(5,9,17,.02),rgba(5,9,17,.64)),url('${refs[1].img}')` }} /><div className="insight"><span>FASHION BRAIN · V2</span><strong>{intelligenceCount}</strong><p>structured wear, fabric, context and aesthetic records.</p></div></div></section>

    <section className="premiumJourney wrap"><div className="sectionHead"><p className="eyebrow">THE EXPERIENCE</p><h2>Not a chatbot. A guided design process with a memory of every decision.</h2></div><div className="journeyRail"><article><span>01</span><h3>Read the fabric</h3><p>Classify material, then judge breathability, drape, structure and the garments it can credibly become.</p></article><article><span>02</span><h3>Set the context</h3><p>Occasion, venue, climate, formality, impression and fit shape the brief.</p></article><article><span>03</span><h3>Build the outfit</h3><p>Safe, Elevated and Statement directions assign the uploaded fabric to its best garment role.</p></article><article><span>04</span><h3>Refine & hand off</h3><p>Lock components, visualize, save, then pass the exact specification to the human atelier.</p></article></div></section>

    <section className="section wrap" id="garments"><div className="sectionHead"><p className="eyebrow">FASHION BRAIN · V2</p><h2>A system that understands what a garment is, what a fabric can do, and whether the occasion supports the combination.</h2></div><div className="stats"><Link href="/knowledge"><span>WEAR TYPES</span><strong>{knowledgeSummary.garments}</strong><p>Shirts, trousers, tailoring and Indian formalwear with construction signals.</p></Link><Link href="/knowledge" id="fabrics"><span>FABRICS</span><strong>{knowledgeSummary.fabrics}</strong><p>Linen, cotton, TR/PV, TR-Wool, wool and occasion-focused specialist fabrics.</p></Link><Link href="/knowledge"><span>CONTEXTS</span><strong>{knowledgeSummary.contexts}</strong><p>Occasion, venue, time, climate and formality logic.</p></Link><Link href="/knowledge"><span>AESTHETICS</span><strong>{knowledgeSummary.aesthetics}</strong><p>Designer identities encoded as measurable signals.</p></Link></div></section>

    <section className="section wrap"><div className="sectionHead"><p className="eyebrow">VISUAL WORLD</p><h2>Tailoring craft, translated into a darker digital language.</h2></div><div className="refGrid">{refs.map((r, i) => <article key={r.title} className={i === 0 ? "ref wide" : "ref"} style={{ backgroundImage: `linear-gradient(180deg,rgba(6,11,20,.05),rgba(6,11,20,.9)),url('${r.img}')` }}><div><span>REFERENCE</span><h3>{r.title}</h3><p>{r.copy}</p></div></article>)}</div></section>

    <section className="section wrap" id="atelier"><div className="sectionHead"><p className="eyebrow">DIGITAL → PHYSICAL</p><h2>The customer-approved design now arrives at the store with its fabric judgement and exact specification intact.</h2></div><div className="phase7Status"><div><span>PRODUCT STATUS</span><strong>Fashion Intelligence V2 + Phase 8 atelier handoff.</strong></div><Link href="/atelier">Open atelier queue →</Link></div></section>
  </AppShell>;
}
