-- LLinen Earth cloud memory
--
-- Canonical production migration:
--   supabase/migrations/20260920_style_events_hardening.sql
--
-- Current schema contract: v5
--
-- The migration creates public.style_events as an append-only event ledger,
-- enables RLS, removes direct anon/authenticated access, grants the server role
-- only SELECT + INSERT, and installs server-only health/version RPCs.
--
-- Required Vercel server-only environment variables:
--   SUPABASE_URL
--   SUPABASE_SECRET_KEY              (preferred modern server secret)
--   SUPABASE_SERVICE_ROLE_KEY        (legacy fallback only)
--   LLINEN_OPERATOR_SYNC_TOKEN
--   LLINEN_OPERATOR_PASSWORD_HASH
--   LLINEN_OPERATOR_SESSION_SECRET
--   LLINEN_MEMORY_SESSION_SECRET
--
-- Public website clients never receive the elevated Supabase key.
-- Next.js Route Handlers validate and persist events server-side.
--
-- Desktop LLinen Earth OS:
--   1. Pair /api/operator/sync with LLINEN_OPERATOR_SYNC_TOKEN.
--   2. The token is stored in Windows Credential Manager.
--   3. Desktop pushes local operator events and pulls website events.
--   4. Event IDs make uploads idempotent.
--   5. received_at + id is the deterministic pull cursor.
--   6. Pairing health verifies the cloud schema before real sync.
--
-- Verification after applying the migration:
--   npm run cloud:check
--
-- That command validates:
--   • style_events exists
--   • RLS is enabled
--   • anon/authenticated have no direct access
--   • the server role has SELECT/INSERT only
--   • schema version is exactly v5
--
-- Do not hand-edit production data in style_events. Business history is
-- append-only; corrections should be new events.
